### ISSUE TITLE
cnspec 10.3.0 - docker cnspec shell host crash

### ISSUE THREAD

**Issue by schnipschnap** [mondoohq/cnspec#1113]
When executing sudo `docker run --rm mondoo/cnspec:latest shell host s01-core.calligo.cloud` we run into the following error:

```
christian@Christian-Gross ~ % sudo docker run --rm mondoo/cnspec:latest shell host s01-core.calligo.cloud
Unable to find image 'mondoo/cnspec:latest' locally
2024/02/14 10:46:14 must use ASL logging (which requires CGO) if running as root
latest: Pulling from mondoo/cnspec
bca4290a9639: Pull complete 
91d523b66e04: Pull complete 
1d7e248ceb27: Pull complete 
c2defb4bb744: Pull complete 
Digest: sha256:b6ad3993c98974d7bc56679e6e3f00c99315849c5637cc3ba886e18a5ee0821f
Status: Downloaded newer image for mondoo/cnspec:latest
! can't find any paths for providers, none are configured system-path=/opt/mondoo/providers
→ installing provider 'network' version=9.2.0
→ successfully installed network provider path=/opt/mondoo/providers/network version=9.2.0
→ no Mondoo configuration file provided, using defaults
→ connected to Network Host
x no service account configured
panic: inappropriate ioctl for device [recovered]
	panic: inappropriate ioctl for device

goroutine 1 [running]:
go.mondoo.com/cnquery/v10/providers-sdk/v1/upstream/health.ReportPanic({0x191da4b, 0x6}, {0x1fc9b5c, 0x6}, {0x1fca448, 0x7}, {0x0, 0x0, 0x40000021c0?})
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery/v10@v10.3.0/providers-sdk/v1/upstream/health/errors.go:30 +0x110
panic({0x16c9e80?, 0x2e00ee8?})
	/home/runner/_work/_tool/go/1.22.0/x64/src/runtime/panic.go:770 +0x124
go.mondoo.com/cnquery/v10/cli/shell.(*Shell).backupTerminalSettings(...)
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery/v10@v10.3.0/cli/shell/terminal_posix.go:22
go.mondoo.com/cnquery/v10/cli/shell.(*Shell).RunInteractive(0x400711c000, {0x0, 0x0})
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery/v10@v10.3.0/cli/shell/shell.go:141 +0x72c
go.mondoo.com/cnquery/v10/apps/cnquery/cmd.StartShell(0x40001a6540, 0x400099d920)
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery/v10@v10.3.0/apps/cnquery/cmd/shell.go:152 +0x7a8
go.mondoo.com/cnspec/v10/apps/cnspec/cmd.init.func30(0x2fc5ac0?, 0x40001a6540, 0x4000aa4460?)
	/home/runner/_work/cnspec/cnspec/apps/cnspec/cmd/shell.go:43 +0xa8
go.mondoo.com/cnquery/v10/cli/providers.setConnector.func2(0x4006f70008, {0x4000aa0700, 0x1, 0x1})
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery/v10@v10.3.0/cli/providers/providers.go:496 +0x89c
github.com/spf13/cobra.(*Command).execute(0x4006f70008, {0x4000aa06d0, 0x1, 0x1})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0x828
github.com/spf13/cobra.(*Command).ExecuteC(0x2f94240)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
go.mondoo.com/cnspec/v10/apps/cnspec/cmd.Execute()
	/home/runner/_work/cnspec/cnspec/apps/cnspec/cmd/root.go:120 +0x88
main.main()
	/home/runner/_work/cnspec/cnspec/apps/cnspec/cnspec.go:14 +0x7c

```

- OS: macOS and Linux

**Comment by imilchev** [comment]
in order to run `cnspec shell` you need to be running in "interactive" mode. If you use `docker run --rm mondoo/cnspec:latest shell host s01-core.calligo.cloud`, it should work.

@schnipschnap please re-test and if it works, close the issue

**Comment by schnipschnap** [comment]
Thanks @imilchev that works
