### ISSUE TITLE
cnspec.service on Fedora40 leaks dbus-daemon processes, filling up inotify-watch slots

### ISSUE THREAD

**Issue by azrdev** [mondoohq/cnspec#1382]
After some uptime, cnspec systemd unit accumulates a lot of `dbus-daemon` processes which block resources. 

## **To Reproduce**

After some uptime, I notice high CPU load (100% on one core) from rsyslogd.service. stopping or Restarting it succeeds with a red (error?) message "Failed to allocate directory watch: Too many open files" . journalctl of that unit tells me that immediately after startup it logs once
`Jul 24 14:06:32 myhostname rsyslogd[2994022]: imjournal from <myhostname:flatpak>: begin to drop messages due to rate-limiting`.

`systemctl status cnspec` tells me there is no cnspec running (anymore) but several hundred processes `/usr/bin/dbus-daemon --syslog --fork --print-pid 4 --print-address 6 --session` in that unit. `systemctl stop cnspec` does not change that, `systemctl kill cnspec` kills the dbus processes, and lets me restart rsyslog without it clogging ressources.

## **Expected behavior**
no process leaks, no inotify-watch slot clogging

## **Desktop (please complete the following information):**

- OS: Fedora Linux
- OS Version: 40
- cnspec rpm version: cnspec-11.11.0-1.x86_64
- Browser if applicable: -
- Browser Version: -

## **Additional context**
mondoo customer with own policy :)

**Comment by azrdev** [comment]
probably the leak is only triggered by a cnspec crash in the first place. journal/syslog:

~~~
Aug 02 10:13:47 cnspec[1275191]: panic: interface conversion: interface {} is nil, not string
Aug 02 10:13:47 cnspec[1275191]: goroutine 17532 [running]:
Aug 02 10:13:47 cnspec[1275191]: go.mondoo.com/cnquery/v11/llx.stringInArray(0x372b938?, 0xc002f68f00, 0xc003584442?, 0x2?)
Aug 02 10:13:47 cnspec[1275191]:         /home/runner/go/pkg/mod/go.mondoo.com/cnquery/v11@v11.14.1-0.20240724175750-e6e001675bad/llx/builtin_simple.go:2247 +0x17c
Aug 02 10:13:47 cnspec[1275191]: go.mondoo.com/cnquery/v11/llx.(*blockExecutor).runBoundFunction(0xc00365a620, 0xc002f68f00, 0xc0035964b0, 0x200000006)
Aug 02 10:13:47 cnspec[1275191]:         /home/runner/go/pkg/mod/go.mondoo.com/cnquery/v11@v11.14.1-0.20240724175750-e6e001675bad/llx/builtin.go:857 +0x108
Aug 02 10:13:47 cnspec[1275191]: go.mondoo.com/cnquery/v11/llx.(*blockExecutor).runFunction(0xc00365a620, 0xc0035964b0, 0x200000006)
Aug 02 10:13:47 cnspec[1275191]:         /home/runner/go/pkg/mod/go.mondoo.com/cnquery/v11@v11.14.1-0.20240724175750-e6e001675bad/llx/llx.go:812 +0x173
Aug 02 10:13:47 cnspec[1275191]: go.mondoo.com/cnquery/v11/llx.(*blockExecutor).runChunk(0xc00365a620, 0x1d44b80?, 0x200000006)
Aug 02 10:13:47 cnspec[1275191]:         /home/runner/go/pkg/mod/go.mondoo.com/cnquery/v11@v11.14.1-0.20240724175750-e6e001675bad/llx/llx.go:829 +0x225
Aug 02 10:13:47 cnspec[1275191]: go.mondoo.com/cnquery/v11/llx.(*blockExecutor).runRef(0xc0030d14c0?, 0xc00303f740?)
Aug 02 10:13:47 cnspec[1275191]:         /home/runner/go/pkg/mod/go.mondoo.com/cnquery/v11@v11.14.1-0.20240724175750-e6e001675bad/llx/llx.go:854 +0xd9
Aug 02 10:13:47 cnspec[1275191]: go.mondoo.com/cnquery/v11/llx.(*blockExecutor).runChain(0xc00365a620, 0xc00303f740?)
Aug 02 10:13:47 cnspec[1275191]:         /home/runner/go/pkg/mod/go.mondoo.com/cnquery/v11@v11.14.1-0.20240724175750-e6e001675bad/llx/llx.go:886 +0x9c
Aug 02 10:13:47 cnspec[1275191]: go.mondoo.com/cnquery/v11/llx.(*blockExecutor).triggerChain(0xc00365a620, 0x200000004, 0xc002f68f00)
Aug 02 10:13:47 cnspec[1275191]:         /home/runner/go/pkg/mod/go.mondoo.com/cnquery/v11@v11.14.1-0.20240724175750-e6e001675bad/llx/llx.go:958 +0x365
Aug 02 10:13:47 cnspec[1275191]: go.mondoo.com/cnquery/v11/llx.runResourceFunction.func1({0x1c690c0, 0xc002e53630}, {0x0, 0x0})
Aug 02 10:13:47 cnspec[1275191]:         /home/runner/go/pkg/mod/go.mondoo.com/cnquery/v11@v11.14.1-0.20240724175750-e6e001675bad/llx/builtin.go:815 +0x219
Aug 02 10:13:47 cnspec[1275191]: go.mondoo.com/cnquery/v11/providers.(*Runtime).WatchAndUpdate(0xc00043e980, {0x27cef98, 0xc002caa160}, {0xc003584430, 0x7}, {0xc003e5a880, 0x31}, 0xc002f68a50)
Aug 02 10:13:47 cnspec[1275191]:         /home/runner/go/pkg/mod/go.mondoo.com/cnquery/v11@v11.14.1-0.20240724175750-e6e001675bad/providers/runtime.go:346 +0xe2
Aug 02 10:13:47 cnspec[1275191]: go.mondoo.com/cnquery/v11/llx.runResourceFunction(0xc00365a620, 0x5?, 0xc003596410, 0x200000004)
Aug 02 10:13:47 cnspec[1275191]:         /home/runner/go/pkg/mod/go.mondoo.com/cnquery/v11@v11.14.1-0.20240724175750-e6e001675bad/llx/builtin.go:796 +0x26d
Aug 02 10:13:47 cnspec[1275191]: go.mondoo.com/cnquery/v11/llx.(*blockExecutor).runBoundFunction(0xc00365a620, 0xc00303ecf0, 0xc003596410, 0x200000004)
Aug 02 10:13:47 cnspec[1275191]:         /home/runner/go/pkg/mod/go.mondoo.com/cnquery/v11@v11.14.1-0.20240724175750-e6e001675bad/llx/builtin.go:870 +0xe5
Aug 02 10:13:47 cnspec[1275191]: go.mondoo.com/cnquery/v11/llx.(*blockExecutor).runFunction(0xc00365a620, 0xc003596410, 0x200000004)
Aug 02 10:13:47 cnspec[1275191]:         /home/runner/go/pkg/mod/go.mondoo.com/cnquery/v11@v11.14.1-0.20240724175750-e6e001675bad/llx/llx.go:812 +0x173
Aug 02 10:13:47 cnspec[1275191]: go.mondoo.com/cnquery/v11/llx.(*blockExecutor).runChunk(0xc00365a620, 0x1d44b80?, 0x200000004)
Aug 02 10:13:47 cnspec[1275191]:         /home/runner/go/pkg/mod/go.mondoo.com/cnquery/v11@v11.14.1-0.20240724175750-e6e001675bad/llx/llx.go:829 +0x225
Aug 02 10:13:47 cnspec[1275191]: go.mondoo.com/cnquery/v11/llx.(*blockExecutor).runRef(0xc0030d14c0?, 0xc00303f740?)
Aug 02 10:13:47 cnspec[1275191]:         /home/runner/go/pkg/mod/go.mondoo.com/cnquery/v11@v11.14.1-0.20240724175750-e6e001675bad/llx/llx.go:854 +0xd9
Aug 02 10:13:47 cnspec[1275191]: go.mondoo.com/cnquery/v11/llx.(*blockExecutor).runChain(0xc00365a620, 0xc00303f740?)
Aug 02 10:13:47 cnspec[1275191]:         /home/runner/go/pkg/mod/go.mondoo.com/cnquery/v11@v11.14.1-0.20240724175750-e6e001675bad/llx/llx.go:886 +0x9c
Aug 02 10:13:47 cnspec[1275191]: go.mondoo.com/cnquery/v11/llx.(*blockExecutor).triggerChain(0xc00365a620, 0x200000002, 0xc002f687e0)
Aug 02 10:13:47 cnspec[1275191]:         /home/runner/go/pkg/mod/go.mondoo.com/cnquery/v11@v11.14.1-0.20240724175750-e6e001675bad/llx/llx.go:958 +0x365
Aug 02 10:13:47 cnspec[1275191]: go.mondoo.com/cnquery/v11/llx.runResourceFunction.func1({0x1c690c0, 0xc002e52fa0}, {0x0, 0x0})
Aug 02 10:13:47 cnspec[1275191]:         /home/runner/go/pkg/mod/go.mondoo.com/cnquery/v11@v11.14.1-0.20240724175750-e6e001675bad/llx/builtin.go:815 +0x219
Aug 02 10:13:47 cnspec[1275191]: go.mondoo.com/cnquery/v11/providers.(*Runtime).WatchAndUpdate(0xc00043e980, {0x27cef98, 0xc002caa160}, {0xc003584425, 0x7}, {0xc003d35f40, 0x31}, 0xc00303f8c0)
Aug 02 10:13:47 cnspec[1275191]:         /home/runner/go/pkg/mod/go.mondoo.com/cnquery/v11@v11.14.1-0.20240724175750-e6e001675bad/providers/runtime.go:346 +0xe2
Aug 02 10:13:47 cnspec[1275191]: go.mondoo.com/cnquery/v11/llx.runResourceFunction(0xc00365a620, 0x5?, 0xc003596370, 0x200000002)
Aug 02 10:13:47 cnspec[1275191]:         /home/runner/go/pkg/mod/go.mondoo.com/cnquery/v11@v11.14.1-0.20240724175750-e6e001675bad/llx/builtin.go:796 +0x26d
Aug 02 10:13:47 cnspec[1275191]: go.mondoo.com/cnquery/v11/llx.(*blockExecutor).runBoundFunction(0xc00365a620, 0xc00303ecf0, 0xc003596370, 0x200000002)
Aug 02 10:13:47 cnspec[1275191]:         /home/runner/go/pkg/mod/go.mondoo.com/cnquery/v11@v11.14.1-0.20240724175750-e6e001675bad/llx/builtin.go:870 +0xe5
Aug 02 10:13:47 cnspec[1275191]: go.mondoo.com/cnquery/v11/llx.(*blockExecutor).runFunction(0xc00365a620, 0xc003596370, 0x200000002)
Aug 02 10:13:47 cnspec[1275191]:         /home/runner/go/pkg/mod/go.mondoo.com/cnquery/v11@v11.14.1-0.20240724175750-e6e001675bad/llx/llx.go:812 +0x173
Aug 02 10:13:47 cnspec[1275191]: go.mondoo.com/cnquery/v11/llx.(*blockExecutor).runChunk(0xc00365a620, 0x1d44b80?, 0x200000002)
Aug 02 10:13:47 cnspec[1275191]:         /home/runner/go/pkg/mod/go.mondoo.com/cnquery/v11@v11.14.1-0.20240724175750-e6e001675bad/llx/llx.go:829 +0x225
Aug 02 10:13:47 cnspec[1275191]: go.mondoo.com/cnquery/v11/llx.(*blockExecutor).runRef(0xc0030d14c0?, 0x10?)
Aug 02 10:13:47 cnspec[1275191]:         /home/runner/go/pkg/mod/go.mondoo.com/cnquery/v11@v11.14.1-0.20240724175750-e6e001675bad/llx/llx.go:854 +0xd9
Aug 02 10:13:47 cnspec[1275191]: go.mondoo.com/cnquery/v11/llx.(*blockExecutor).runChain(0xc00365a620, 0x20a5475?)
Aug 02 10:13:47 cnspec[1275191]:         /home/runner/go/pkg/mod/go.mondoo.com/cnquery/v11@v11.14.1-0.20240724175750-e6e001675bad/llx/llx.go:886 +0x9c
Aug 02 10:13:47 cnspec[1275191]: go.mondoo.com/cnquery/v11/llx.(*blockExecutor).run(0xc00365a620)
Aug 02 10:13:47 cnspec[1275191]:         /home/runner/go/pkg/mod/go.mondoo.com/cnquery/v11@v11.14.1-0.20240724175750-e6e001675bad/llx/llx.go:354 +0x2d7
Aug 02 10:13:47 cnspec[1275191]: go.mondoo.com/cnquery/v11/llx.(*blockExecutor).runFunctionBlock(0xc0031ebdc0, {0xc002d2f2d0, 0x1, 0xc001c7d040?}, 0x200000000, 0xc002656f78)
Aug 02 10:13:47 cnspec[1275191]:         /home/runner/go/pkg/mod/go.mondoo.com/cnquery/v11@v11.14.1-0.20240724175750-e6e001675bad/llx/llx.go:585 +0x17c
Aug 02 10:13:47 cnspec[1275191]: go.mondoo.com/cnquery/v11/llx.(*blockExecutor).runFunctionBlocks(0xc0031ebdc0, {0xc002f76c60, 0xb, 0xc001969c01?}, 0x200000000, 0x10fcdec?)
Aug 02 10:13:47 cnspec[1275191]:         /home/runner/go/pkg/mod/go.mondoo.com/cnquery/v11@v11.14.1-0.20240724175750-e6e001675bad/llx/llx.go:556 +0x107
Aug 02 10:13:47 cnspec[1275191]: go.mondoo.com/cnquery/v11/llx._arrayWhereV2(0xc0031ebdc0, 0xc00303ec00, 0xc0035961e0, 0x100000003, 0x0)
Aug 02 10:13:47 cnspec[1275191]:         /home/runner/go/pkg/mod/go.mondoo.com/cnquery/v11@v11.14.1-0.20240724175750-e6e001675bad/llx/builtin_array.go:269 +0x47e
Aug 02 10:13:47 cnspec[1275191]: go.mondoo.com/cnquery/v11/llx.arrayWhereV2(0xc000a8270a?, 0x6?, 0xc0035843a6?, 0x5?)
Aug 02 10:13:47 cnspec[1275191]:         /home/runner/go/pkg/mod/go.mondoo.com/cnquery/v11@v11.14.1-0.20240724175750-e6e001675bad/llx/builtin_array.go:297 +0x15
Aug 02 10:13:47 cnspec[1275191]: go.mondoo.com/cnquery/v11/llx.(*blockExecutor).runBoundFunction(0xc0031ebdc0, 0xc00303ec00, 0xc0035961e0, 0x100000003)
Aug 02 10:13:47 cnspec[1275191]:         /home/runner/go/pkg/mod/go.mondoo.com/cnquery/v11@v11.14.1-0.20240724175750-e6e001675bad/llx/builtin.go:857 +0x108
Aug 02 10:13:47 cnspec[1275191]: go.mondoo.com/cnquery/v11/llx.(*blockExecutor).runFunction(0xc0031ebdc0, 0xc0035961e0, 0x100000003)
Aug 02 10:13:47 cnspec[1275191]:         /home/runner/go/pkg/mod/go.mondoo.com/cnquery/v11@v11.14.1-0.20240724175750-e6e001675bad/llx/llx.go:812 +0x173
Aug 02 10:13:47 cnspec[1275191]: go.mondoo.com/cnquery/v11/llx.(*blockExecutor).runChunk(0xc0031ebdc0, 0x1d44b80?, 0x100000003)
Aug 02 10:13:47 cnspec[1275191]:         /home/runner/go/pkg/mod/go.mondoo.com/cnquery/v11@v11.14.1-0.20240724175750-e6e001675bad/llx/llx.go:829 +0x225
Aug 02 10:13:47 cnspec[1275191]: go.mondoo.com/cnquery/v11/llx.(*blockExecutor).runRef(0xc0030d0cd0?, 0xc001969f80?)
Aug 02 10:13:47 cnspec[1275191]:         /home/runner/go/pkg/mod/go.mondoo.com/cnquery/v11@v11.14.1-0.20240724175750-e6e001675bad/llx/llx.go:854 +0xd9
Aug 02 10:13:47 cnspec[1275191]: go.mondoo.com/cnquery/v11/llx.(*blockExecutor).runChain(0xc0031ebdc0, 0xc002fe1b00?)
Aug 02 10:13:47 cnspec[1275191]:         /home/runner/go/pkg/mod/go.mondoo.com/cnquery/v11@v11.14.1-0.20240724175750-e6e001675bad/llx/llx.go:886 +0x9c
Aug 02 10:13:47 cnspec[1275191]: go.mondoo.com/cnquery/v11/llx.(*blockExecutor).triggerChain(0xc0031ebdc0, 0x100000002, 0xc00303ec00)
Aug 02 10:13:47 cnspec[1275191]:         /home/runner/go/pkg/mod/go.mondoo.com/cnquery/v11@v11.14.1-0.20240724175750-e6e001675bad/llx/llx.go:958 +0x365
Aug 02 10:13:47 cnspec[1275191]: go.mondoo.com/cnquery/v11/llx.runResourceFunction.func1({0x1c37ea0, 0xc002656f60}, {0x0, 0x0})
Aug 02 10:13:47 cnspec[1275191]:         /home/runner/go/pkg/mod/go.mondoo.com/cnquery/v11@v11.14.1-0.20240724175750-e6e001675bad/llx/builtin.go:815 +0x219
Aug 02 10:13:47 cnspec[1275191]: go.mondoo.com/cnquery/v11/providers.(*Runtime).WatchAndUpdate(0xc00043e980, {0x27cef98, 0xc002e8c7e0}, {0xc003584395, 0x9}, {0xc003c7db80, 0x31}, 0xc00311a150)
Aug 02 10:13:47 cnspec[1275191]:         /home/runner/go/pkg/mod/go.mondoo.com/cnquery/v11@v11.14.1-0.20240724175750-e6e001675bad/providers/runtime.go:346 +0xe2
Aug 02 10:13:47 cnspec[1275191]: go.mondoo.com/cnquery/v11/llx.runResourceFunction(0xc0031ebdc0, 0x6?, 0xc003596190, 0x100000002)
Aug 02 10:13:47 cnspec[1275191]:         /home/runner/go/pkg/mod/go.mondoo.com/cnquery/v11@v11.14.1-0.20240724175750-e6e001675bad/llx/builtin.go:796 +0x26d
Aug 02 10:13:47 cnspec[1275191]: go.mondoo.com/cnquery/v11/llx.(*blockExecutor).runBoundFunction(0xc0031ebdc0, 0xc00311a090, 0xc003596190, 0x100000002)
Aug 02 10:13:47 cnspec[1275191]:         /home/runner/go/pkg/mod/go.mondoo.com/cnquery/v11@v11.14.1-0.20240724175750-e6e001675bad/llx/builtin.go:870 +0xe5
Aug 02 10:13:47 cnspec[1275191]: go.mondoo.com/cnquery/v11/llx.(*blockExecutor).runFunction(0xc0031ebdc0, 0xc003596190, 0x100000002)
Aug 02 10:13:47 cnspec[1275191]:         /home/runner/go/pkg/mod/go.mondoo.com/cnquery/v11@v11.14.1-0.20240724175750-e6e001675bad/llx/llx.go:812 +0x173
Aug 02 10:13:47 cnspec[1275191]: go.mondoo.com/cnquery/v11/llx.(*blockExecutor).runChunk(0xc0031ebdc0, 0x1d44b80?, 0x100000002)
Aug 02 10:13:47 cnspec[1275191]:         /home/runner/go/pkg/mod/go.mondoo.com/cnquery/v11@v11.14.1-0.20240724175750-e6e001675bad/llx/llx.go:829 +0x225
Aug 02 10:13:47 cnspec[1275191]: go.mondoo.com/cnquery/v11/llx.(*blockExecutor).runRef(0xc0030d0cd0?, 0xc002fe1b00?)
Aug 02 10:13:47 cnspec[1275191]:         /home/runner/go/pkg/mod/go.mondoo.com/cnquery/v11@v11.14.1-0.20240724175750-e6e001675bad/llx/llx.go:854 +0xd9
Aug 02 10:13:47 cnspec[1275191]: go.mondoo.com/cnquery/v11/llx.(*blockExecutor).runChain(0xc0031ebdc0, 0x20a5475?)
Aug 02 10:13:47 cnspec[1275191]:         /home/runner/go/pkg/mod/go.mondoo.com/cnquery/v11@v11.14.1-0.20240724175750-e6e001675bad/llx/llx.go:886 +0x9c
Aug 02 10:13:47 cnspec[1275191]: go.mondoo.com/cnquery/v11/llx.(*blockExecutor).run(0xc0031ebdc0)
Aug 02 10:13:47 cnspec[1275191]:         /home/runner/go/pkg/mod/go.mondoo.com/cnquery/v11@v11.14.1-0.20240724175750-e6e001675bad/llx/llx.go:354 +0x2d7
Aug 02 10:13:47 cnspec[1275191]: go.mondoo.com/cnquery/v11/llx.(*MQLExecutorV2).Run(0xc0035901e0?)
Aug 02 10:13:47 cnspec[1275191]:         /home/runner/go/pkg/mod/go.mondoo.com/cnquery/v11@v11.14.1-0.20240724175750-e6e001675bad/llx/llx.go:286 +0x53
Aug 02 10:13:47 cnspec[1275191]: go.mondoo.com/cnspec/v11/policy/executor/internal.(*executionManager).executeCodeBundle(0xc0005a3040, 0xc0035880a0, 0xc002fe1860, {0x0, 0x0})
Aug 02 10:13:47 cnspec[1275191]:         /home/runner/_work/cnspec/cnspec/policy/executor/internal/execution_manager.go:178 +0x551
Aug 02 10:13:47 cnspec[1275191]: go.mondoo.com/cnspec/v11/policy/executor/internal.(*executionManager).Start.func1()
Aug 02 10:13:47 cnspec[1275191]:         /home/runner/_work/cnspec/cnspec/policy/executor/internal/execution_manager.go:95 +0x1cb
Aug 02 10:13:47 cnspec[1275191]: created by go.mondoo.com/cnspec/v11/policy/executor/internal.(*executionManager).Start in goroutine 146
Aug 02 10:13:47 cnspec[1275191]:         /home/runner/_work/cnspec/cnspec/policy/executor/internal/execution_manager.go:64 +0x65
Aug 02 10:13:47 systemd[1]: cnspec.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 02 10:13:47 systemd[1]: cnspec.service: Failed with result 'exit-code'.
Aug 02 10:13:47 systemd[1]: cnspec.service: Unit process 1217325 (dbus-daemon) remains running after unit stopped.
Aug 02 10:13:47 systemd[1]: cnspec.service: Unit process 1220660 (dbus-daemon) remains running after unit stopped.
Aug 02 10:13:47 systemd[1]: cnspec.service: Unit process 1223822 (dbus-daemon) remains running after unit stopped.
Aug 02 10:13:47 systemd[1]: cnspec.service: Unit process 1227011 (dbus-daemon) remains running after unit stopped.
Aug 02 10:13:47 systemd[1]: cnspec.service: Unit process 1230195 (dbus-daemon) remains running after unit stopped.
Aug 02 10:13:47 systemd[1]: cnspec.service: Unit process 1233331 (dbus-daemon) remains running after unit stopped.
Aug 02 10:13:47 systemd[1]: cnspec.service: Unit process 1236467 (dbus-daemon) remains running after unit stopped.
Aug 02 10:13:47 systemd[1]: cnspec.service: Unit process 1239580 (dbus-daemon) remains running after unit stopped.
Aug 02 10:13:47 systemd[1]: cnspec.service: Unit process 1242791 (dbus-daemon) remains running after unit stopped.
Aug 02 10:13:47 systemd[1]: cnspec.service: Unit process 1245900 (dbus-daemon) remains running after unit stopped.
Aug 02 10:13:47 systemd[1]: cnspec.service: Unit process 1249013 (dbus-daemon) remains running after unit stopped.
Aug 02 10:13:47 systemd[1]: cnspec.service: Unit process 1252269 (dbus-daemon) remains running after unit stopped.
Aug 02 10:13:47 systemd[1]: cnspec.service: Unit process 1255466 (dbus-daemon) remains running after unit stopped.
Aug 02 10:13:47 systemd[1]: cnspec.service: Unit process 1258654 (dbus-daemon) remains running after unit stopped.
Aug 02 10:13:47 systemd[1]: cnspec.service: Unit process 1261699 (dbus-daemon) remains running after unit stopped.
Aug 02 10:13:47 systemd[1]: cnspec.service: Unit process 1265092 (dbus-daemon) remains running after unit stopped.
Aug 02 10:13:47 systemd[1]: cnspec.service: Unit process 1268659 (dbus-daemon) remains running after unit stopped.
Aug 02 10:13:47 systemd[1]: cnspec.service: Unit process 1271931 (dbus-daemon) remains running after unit stopped.
Aug 02 10:13:47 systemd[1]: cnspec.service: Unit process 1275203 (dbus-daemon) remains running after unit stopped.
Aug 02 10:13:47 systemd[1]: cnspec.service: Unit process 1275265 (os) remains running after unit stopped.
Aug 02 10:13:47 audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=cnspec comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
Aug 02 10:13:47 systemd[1]: cnspec.service: Consumed 48.503s CPU time, 289.3M memory peak, 0B memory swap peak.

**Comment by atomic111** [comment]
https://github.com/mondoohq/cnspec/issues/1382

**Comment by slntopp** [comment]
Panic will be fixed with https://github.com/mondoohq/cnquery/pull/4812

**Comment by slntopp** [comment]
Hi @azrdev 
That fix was merged and released, please try it again with the new cnspec release (v11.29.0) and share if the leak persists.

Also, could you please share if this machine has Fedora with any DE?

**Comment by azrdev** [comment]
Thanks, will try! I'm running Fedora, currently version 40, with KDE (from distro packages)
