### ISSUE TITLE
cnspec crash to scan suse 15.3 on PowerPC

### ISSUE THREAD

**Issue by atomic111** [mondoohq/cnspec#453]
```bash
cnspec scan ssh root@target -i ~/.ssh/id_rsa
→ loaded configuration from /root/.config/mondoo/mondoo.yml using source default
→ using service account credentials
→ discover related assets for 1 asset(s)
→ resolved assets resolved-assets=1

panic: runtime error: index out of range [1] with length 0


goroutine 123 [running]:

[go.mondoo.com/cnquery/resources/packs/core/processes.ParseLinuxPsResult({0x9cb9440](http://go.mondoo.com/cnquery/resources/packs/core/processes.ParseLinuxPsResult(%7B0x9cb9440)?, 0xc001a6d2f0?})

        /home/runner/go/pkg/mod/[go.mondoo.com/cnquery@v0.0.0-20230315170958-9177e86c4a0a/resources/packs/core/processes/unixps.go:57](http://go.mondoo.com/cnquery@v0.0.0-20230315170958-9177e86c4a0a/resources/packs/core/processes/unixps.go:57) +0x4f8

[go.mondoo.com/cnquery/resources/packs/core/processes.(*UnixProcessManager).List(0xc000b0b260)](http://go.mondoo.com/cnquery/resources/packs/core/processes.(*UnixProcessManager).List(0xc000b0b260))

        /home/runner/go/pkg/mod/[go.mondoo.com/cnquery@v0.0.0-20230315170958-9177e86c4a0a/resources/packs/core/processes/unixps.go:153](http://go.mondoo.com/cnquery@v0.0.0-20230315170958-9177e86c4a0a/resources/packs/core/processes/unixps.go:153) +0x124

[go.mondoo.com/cnquery/resources/packs/core.(*mqlProcesses).GetList(0xc00063b528)](http://go.mondoo.com/cnquery/resources/packs/core.(*mqlProcesses).GetList(0xc00063b528))

        /home/runner/go/pkg/mod/[go.mondoo.com/cnquery@v0.0.0-20230315170958-9177e86c4a0a/resources/packs/core/processes.go:175](http://go.mondoo.com/cnquery@v0.0.0-20230315170958-9177e86c4a0a/resources/packs/core/processes.go:175) +0x70

[go.mondoo.com/cnquery/resources/packs/core.(*mqlProcesses).ComputeList(0xc00063b528)](http://go.mondoo.com/cnquery/resources/packs/core.(*mqlProcesses).ComputeList(0xc00063b528))

        /home/runner/go/pkg/mod/[go.mondoo.com/cnquery@v0.0.0-20230315170958-9177e86c4a0a/resources/packs/core/core.lr.go:8831](http://go.mondoo.com/cnquery@v0.0.0-20230315170958-9177e86c4a0a/resources/packs/core/core.lr.go:8831) +0x60

[go.mondoo.com/cnquery/resources/packs/core.(*mqlProcesses).MqlCompute(0xc001f023c0](http://go.mondoo.com/cnquery/resources/packs/core.(*mqlProcesses).MqlCompute(0xc001f023c0)?, {0x8af269f, 0x4})

        /home/runner/go/pkg/mod/[go.mondoo.com/cnquery@v0.0.0-20230315170958-9177e86c4a0a/resources/packs/core/core.lr.go:8819](http://go.mondoo.com/cnquery@v0.0.0-20230315170958-9177e86c4a0a/resources/packs/core/core.lr.go:8819) +0xb8

[go.mondoo.com/cnquery/resources.(*Runtime).WatchAndUpdate(0xc001f02400](http://go.mondoo.com/cnquery/resources.(*Runtime).WatchAndUpdate(0xc001f02400), {0x9d91a40, 0xc00063b528}, {0x8af269f, 0x4}, {0xc001a645c0, 0x31}, 0xc001a6d200)

        /home/runner/go/pkg/mod/[go.mondoo.com/cnquery@v0.0.0-20230315170958-9177e86c4a0a/resources/runtime.go:348](http://go.mondoo.com/cnquery@v0.0.0-20230315170958-9177e86c4a0a/resources/runtime.go:348) +0x374

[go.mondoo.com/cnquery/llx.runResourceFunction(0xc000255f80](http://go.mondoo.com/cnquery/llx.runResourceFunction(0xc000255f80), 0xc001a6d110, 0xc00192a050, 0x100000007)

        /home/runner/go/pkg/mod/[go.mondoo.com/cnquery@v0.0.0-20230315170958-9177e86c4a0a/llx/builtin.go:712](http://go.mondoo.com/cnquery@v0.0.0-20230315170958-9177e86c4a0a/llx/builtin.go:712) +0x210

[go.mondoo.com/cnquery/llx.(*blockExecutor).runBoundFunction(0xc000255f80](http://go.mondoo.com/cnquery/llx.(*blockExecutor).runBoundFunction(0xc000255f80), 0xc001a6d110, 0xc00192a050, 0x20?)

        /home/runner/go/pkg/mod/[go.mondoo.com/cnquery@v0.0.0-20230315170958-9177e86c4a0a/llx/builtin.go:795](http://go.mondoo.com/cnquery@v0.0.0-20230315170958-9177e86c4a0a/llx/builtin.go:795) +0x130

[go.mondoo.com/cnquery/llx.(*blockExecutor).runFunction(0xc000255f80](http://go.mondoo.com/cnquery/llx.(*blockExecutor).runFunction(0xc000255f80), 0xc00192a050, 0x861f4?)

        /home/runner/go/pkg/mod/[go.mondoo.com/cnquery@v0.0.0-20230315170958-9177e86c4a0a/llx/llx.go:764](http://go.mondoo.com/cnquery@v0.0.0-20230315170958-9177e86c4a0a/llx/llx.go:764) +0x108

[go.mondoo.com/cnquery/llx.(*blockExecutor).runChunk(0xc000255f80](http://go.mondoo.com/cnquery/llx.(*blockExecutor).runChunk(0xc000255f80), 0xc001a6cf90?, 0x100000007?)

        /home/runner/go/pkg/mod/[go.mondoo.com/cnquery@v0.0.0-20230315170958-9177e86c4a0a/llx/llx.go:781](http://go.mondoo.com/cnquery@v0.0.0-20230315170958-9177e86c4a0a/llx/llx.go:781) +0x288

[go.mondoo.com/cnquery/llx.(*blockExecutor).runRef(0xc0005c5170](http://go.mondoo.com/cnquery/llx.(*blockExecutor).runRef(0xc0005c5170)?, 0xc001a6cf60?)

        /home/runner/go/pkg/mod/[go.mondoo.com/cnquery@v0.0.0-20230315170958-9177e86c4a0a/llx/llx.go:806](http://go.mondoo.com/cnquery@v0.0.0-20230315170958-9177e86c4a0a/llx/llx.go:806) +0x124

[go.mondoo.com/cnquery/llx.(*blockExecutor).runChain(0xc000255f80](http://go.mondoo.com/cnquery/llx.(*blockExecutor).runChain(0xc000255f80), 0x8afc625?)

        /home/runner/go/pkg/mod/[go.mondoo.com/cnquery@v0.0.0-20230315170958-9177e86c4a0a/llx/llx.go:838](http://go.mondoo.com/cnquery@v0.0.0-20230315170958-9177e86c4a0a/llx/llx.go:838) +0xb0

[go.mondoo.com/cnquery/llx.(*blockExecutor).run(0xc000255f80)](http://go.mondoo.com/cnquery/llx.(*blockExecutor).run(0xc000255f80))

        /home/runner/go/pkg/mod/[go.mondoo.com/cnquery@v0.0.0-20230315170958-9177e86c4a0a/llx/llx.go:351](http://go.mondoo.com/cnquery@v0.0.0-20230315170958-9177e86c4a0a/llx/llx.go:351) +0x2b8

[go.mondoo.com/cnquery/llx.(*MQLExecutorV2).Run(0xc003175140](http://go.mondoo.com/cnquery/llx.(*MQLExecutorV2).Run(0xc003175140)?)

        /home/runner/go/pkg/mod/[go.mondoo.com/cnquery@v0.0.0-20230315170958-9177e86c4a0a/llx/llx.go:283](http://go.mondoo.com/cnquery@v0.0.0-20230315170958-9177e86c4a0a/llx/llx.go:283) +0x7c

[go.mondoo.com/cnspec/policy/executor/internal.(*executionManager).executeCodeBundle(0xc001a13a90](http://go.mondoo.com/cnspec/policy/executor/internal.(*executionManager).executeCodeBundle(0xc001a13a90), 0xc001f07040, 0x0?, {0x0, 0x0})

        /home/runner/_work/cnspec/cnspec/policy/executor/internal/execution_manager.go:164 +0x30c

[go.mondoo.com/cnspec/policy/executor/internal.(*executionManager).Start.func1()](http://go.mondoo.com/cnspec/policy/executor/internal.(*executionManager).Start.func1())

        /home/runner/_work/cnspec/cnspec/policy/executor/internal/execution_manager.go:85 +0x18c

created by [go.mondoo.com/cnspec/policy/executor/internal.(*executionManager).Start](http://go.mondoo.com/cnspec/policy/executor/internal.(*executionManager).Start)

        /home/runner/_work/cnspec/cnspec/policy/executor/internal/execution_manager.go:54 +0x84
```

**Comment by chris-rock** [comment]
@atomic111 Thank you for issuing the report. Can you let us know which cnspec version was used?

**Comment by joelddiaz** [comment]
since we are ultimately trying to parse the output of `ps axo pid,pcpu,pmem,vsz,rss,tty,stat,stime,time,uid,command` can we see what the output of what that looks like on the machine that is being scanned?

**Comment by joelddiaz** [comment]
It appears that the `ps` output allows for the possibility of an empty COMMAND column. PR https://github.com/mondoohq/cnquery/pull/1086 should address this.

**Comment by chris-rock** [comment]
This has been fixed
