### ISSUE TITLE
cnspec panics on TF with dynamic value in map key name

### ISSUE THREAD

**Issue by crcsmnky** [mondoohq/cnspec#599]
**Describe the bug**
`cnspec` panic caused by dynamic variables in map key names

**To Reproduce**

1. `cnspec scan terraform test.tf -f mypolicybundle.mql.yaml`

**Expected behavior**
`cnspec` should not panic on valid Terraform

**Screenshots or CLI Output**
```
> cnspec scan terraform test.tf -f ~/Work/terraform-policies/policy
→ loaded configuration from /Users/parikhs/.config/mondoo/mondoo.yml using source default
→ discover related assets for 1 asset(s)
→ resolved assets resolved-assets=1
panic: interface conversion: interface {} is []interface {}, not string

goroutine 26 [running]:
go.mondoo.com/cnquery/resources/packs/terraform.getCtyValue({0x10e4aea10?, 0x14002439ea0?}, 0x14001164780?)
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230523141529-3a14d3038f20/resources/packs/terraform/hcl.go:394 +0xb4c
go.mondoo.com/cnquery/resources/packs/terraform.hclResolvedAttributesToDict(0x140023b62c0?)
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230523141529-3a14d3038f20/resources/packs/terraform/hcl.go:267 +0x178
go.mondoo.com/cnquery/resources/packs/terraform.(*mqlTerraformBlock).GetArguments(0x14000ef0a38?)
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230523141529-3a14d3038f20/resources/packs/terraform/hcl.go:261 +0x68
go.mondoo.com/cnquery/resources/packs/terraform.(*mqlTerraformBlock).ComputeArguments(0x140007ae860)
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230523141529-3a14d3038f20/resources/packs/terraform/terraform.lr.go:1340 +0x48
go.mondoo.com/cnquery/resources/packs/terraform.(*mqlTerraformBlock).MqlCompute(0x1400242f240?, {0x14000724da0, 0x9})
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230523141529-3a14d3038f20/resources/packs/terraform/terraform.lr.go:1308 +0x228
go.mondoo.com/cnquery/resources.(*Runtime).WatchAndUpdate(0x1400242f280, {0x10e4b7320, 0x140007ae860}, {0x14000724da0, 0x9}, {0x1400066cec0, 0x31}, 0x140020f9770)
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230523141529-3a14d3038f20/resources/runtime.go:350 +0x2dc
go.mondoo.com/cnquery/llx.runResourceFunction(0x14000421ce0, 0x14001e6ffb0, 0x14001ae6e10, 0x200000002)
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230523141529-3a14d3038f20/llx/builtin.go:714 +0x1d8
go.mondoo.com/cnquery/llx.(*blockExecutor).runBoundFunction(0x14000421ce0, 0x14001e6ffb0, 0x14001ae6e10, 0x1047fcd84?)
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230523141529-3a14d3038f20/llx/builtin.go:797 +0xf8
go.mondoo.com/cnquery/llx.(*blockExecutor).runFunction(0x14000421ce0, 0x14001ae6e10, 0x14001b373b0?)
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230523141529-3a14d3038f20/llx/llx.go:764 +0xd4
go.mondoo.com/cnquery/llx.(*blockExecutor).runChunk(0x14000421ce0, 0x140020f9620?, 0x200000002?)
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230523141529-3a14d3038f20/llx/llx.go:781 +0x23c
go.mondoo.com/cnquery/llx.(*blockExecutor).runRef(0x1181345b8?, 0x30?)
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230523141529-3a14d3038f20/llx/llx.go:806 +0x100
go.mondoo.com/cnquery/llx.(*blockExecutor).runChain(0x14000421ce0, 0x10b3c8918?)
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230523141529-3a14d3038f20/llx/llx.go:838 +0x8c
go.mondoo.com/cnquery/llx.(*blockExecutor).run(0x14000421ce0)
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230523141529-3a14d3038f20/llx/llx.go:351 +0x290
go.mondoo.com/cnquery/llx.(*blockExecutor).runFunctionBlock(0x14000421960, {0x14000e286a0, 0x1, 0x14001fde3c0?}, 0x200000000, 0x109908308?)
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230523141529-3a14d3038f20/llx/llx.go:582 +0x144
go.mondoo.com/cnquery/llx.(*blockExecutor).runFunctionBlocks(0x14000421960, {0x14001a30380, 0x5, 0x14001e6fe30?}, 0xf800000000000000?, 0x109906248?)
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230523141529-3a14d3038f20/llx/llx.go:553 +0x110
go.mondoo.com/cnquery/llx._arrayWhereV2(0x14000421960, 0x14001e6fda0, 0x14001ae6f00, 0x100000003, 0x0)
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230523141529-3a14d3038f20/llx/builtin_array.go:275 +0x454
go.mondoo.com/cnquery/llx.arrayWhereV2(0x14000dfb380?, 0x11?, 0x14000724d90?, 0x5?)
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230523141529-3a14d3038f20/llx/builtin_array.go:303 +0x20
go.mondoo.com/cnquery/llx.(*blockExecutor).runBoundFunction(0x14000421960, 0x14001e6fda0, 0x14001ae6f00, 0xd0?)
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230523141529-3a14d3038f20/llx/builtin.go:784 +0x120
go.mondoo.com/cnquery/llx.(*blockExecutor).runFunction(0x14000421960, 0x14001ae6f00, 0x14000ef1358?)
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230523141529-3a14d3038f20/llx/llx.go:764 +0xd4
go.mondoo.com/cnquery/llx.(*blockExecutor).runChunk(0x14000421960, 0x14001e6f6e0?, 0x100000003?)
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230523141529-3a14d3038f20/llx/llx.go:781 +0x23c
go.mondoo.com/cnquery/llx.(*blockExecutor).runRef(0x14000ef14f8?, 0x1047b43cc?)
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230523141529-3a14d3038f20/llx/llx.go:806 +0x100
go.mondoo.com/cnquery/llx.(*blockExecutor).runChain(0x14000421960, 0x14001e6f6b0?)
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230523141529-3a14d3038f20/llx/llx.go:838 +0x8c
go.mondoo.com/cnquery/llx.(*blockExecutor).triggerChain(0x14000421960, 0x14001e6f6b0?, 0x14001e6fda0)
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230523141529-3a14d3038f20/llx/llx.go:910 +0x324
go.mondoo.com/cnquery/llx.runResourceFunction.func1({0x10cd0a8c0?, 0x1400000c378}, {0x0?, 0x0})
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230523141529-3a14d3038f20/llx/builtin.go:733 +0x230
go.mondoo.com/cnquery/resources.(*Runtime).WatchAndUpdate(0x1400242f280, {0x10e4b72e0, 0x140007ae018}, {0x14000724d78, 0x6}, {0x1400066ca40, 0x31}, 0x14001e6fb90)
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230523141529-3a14d3038f20/resources/runtime.go:365 +0x38c
go.mondoo.com/cnquery/llx.runResourceFunction(0x14000421960, 0x14001e6fa40, 0x14001ae6cd0, 0x100000002)
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230523141529-3a14d3038f20/llx/builtin.go:714 +0x1d8
go.mondoo.com/cnquery/llx.(*blockExecutor).runBoundFunction(0x14000421960, 0x14001e6fa40, 0x14001ae6cd0, 0x1047fc838?)
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230523141529-3a14d3038f20/llx/builtin.go:797 +0xf8
go.mondoo.com/cnquery/llx.(*blockExecutor).runFunction(0x14000421960, 0x14001ae6cd0, 0x14001b36cf0?)
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230523141529-3a14d3038f20/llx/llx.go:764 +0xd4
go.mondoo.com/cnquery/llx.(*blockExecutor).runChunk(0x14000421960, 0x14001e6f6e0?, 0x100000002?)
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230523141529-3a14d3038f20/llx/llx.go:781 +0x23c
go.mondoo.com/cnquery/llx.(*blockExecutor).runRef(0x14000b03b40?, 0x14001e6f6b0?)
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230523141529-3a14d3038f20/llx/llx.go:806 +0x100
go.mondoo.com/cnquery/llx.(*blockExecutor).runChain(0x14000421960, 0x10b3c8918?)
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230523141529-3a14d3038f20/llx/llx.go:838 +0x8c
go.mondoo.com/cnquery/llx.(*blockExecutor).run(0x14000421960)
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230523141529-3a14d3038f20/llx/llx.go:351 +0x290
go.mondoo.com/cnquery/llx.(*MQLExecutorV2).Run(0x140017c8c00?)
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230523141529-3a14d3038f20/llx/llx.go:283 +0x64
go.mondoo.com/cnspec/policy/executor/internal.(*executionManager).executeCodeBundle(0x14001b1fb30, 0x14001f205a0, 0x14000724e20?, {0x0, 0x0})
	/home/runner/_work/cnspec/cnspec/policy/executor/internal/execution_manager.go:164 +0x288
go.mondoo.com/cnspec/policy/executor/internal.(*executionManager).Start.func1()
	/home/runner/_work/cnspec/cnspec/policy/executor/internal/execution_manager.go:85 +0x15c
created by go.mondoo.com/cnspec/policy/executor/internal.(*executionManager).Start
	/home/runner/_work/cnspec/cnspec/policy/executor/internal/execution_manager.go:54 +0x74
```

**Desktop (please complete the following information):**

- OS: macOS
- OS Version: 13.3.1
- `cnspec` Version: 8.11.0

**Additional context**
`test.tf`:
```
locals {
  blah = {
    "test-${random_string.rando.id}" = {
      type = "something"
    }
  }
}

resource "random_string" "rando" {
  length      = 6
  min_numeric = 6
  special     = false
  upper       = false
}
```

**Comment by vjeffrey** [comment]
oh no! thank you for the detailed issue, we'll fix this and get a patch out this week
