### ISSUE TITLE
Mock scan fails

### ISSUE THREAD

**Issue by atomic111** [mondoohq/cnspec#617]
cnspec version: cnspec v8.13.0 (879f353, unknown)

```bash
cnspec scan mock recording-fail.toml -f windows-server-2022.mql.yaml 

→ loaded configuration from /home/user/.config/mondoo/mondoo.yml using source default
→ using service account credentials
→ discover related assets for 1 asset(s)
→ resolved assets resolved-assets=1

  ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────   0%


panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x64b3fbc]

goroutine 45 [running]:
go.mondoo.com/cnquery/llx.runResourceFunction.func1({0x0?, 0x0}, {0xb4808c0?, 0xc003b47680})
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/builtin.go:718 +0x9c
go.mondoo.com/cnquery/resources.(*Runtime).WatchAndUpdate(0xc0041274c0, {0xb557cc0, 0xc005903710}, {0xc004033e90, 0x14}, {0xc000836cc0, 0x32}, 0xc004a32030)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/resources/runtime.go:365 +0x4dc
go.mondoo.com/cnquery/llx.runResourceFunction(0xc003b4cd20, 0xc004985aa0, 0xc004518640, 0x50000000d)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/builtin.go:716 +0x22f
go.mondoo.com/cnquery/llx.(*blockExecutor).runBoundFunction(0xc003b4cd20, 0xc004985aa0, 0xc004518640, 0xc003b63980?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/builtin.go:799 +0xf2
go.mondoo.com/cnquery/llx.(*blockExecutor).runFunction(0xc003b4cd20, 0xc004518640, 0xc003b45050?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/llx.go:764 +0xde
go.mondoo.com/cnquery/llx.(*blockExecutor).runChunk(0xc003b4cd20, 0xc004985d40?, 0x50000000d?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/llx.go:781 +0x248
go.mondoo.com/cnquery/llx.(*blockExecutor).runRef(0xc003b47510?, 0xc004985c20?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/llx.go:806 +0xef
go.mondoo.com/cnquery/llx.(*blockExecutor).runChain(0xc003b4cd20, 0xa2f6230?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/llx.go:838 +0xa6
go.mondoo.com/cnquery/llx.(*blockExecutor).run(0xc003b4cd20)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/llx.go:351 +0x2d7
go.mondoo.com/cnquery/llx.(*blockExecutor).runFunctionBlock(0xc003b38310, {0xc005903c58, 0x1, 0xc004985ad0?}, 0x500000000, 0xc004985ad0?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/llx.go:582 +0x12f
go.mondoo.com/cnquery/llx.(*blockExecutor).runFunctionBlocks(0xc003b38310, {0xc0044d7e00, 0x1, 0xc000d83b08?}, 0xc0008e35c8?, 0xc0006b2e40?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/llx.go:553 +0x11b
go.mondoo.com/cnquery/llx.arrayBlockListV2(0xc003b38310, 0xc004985a10, 0xc004518370, 0x10000000a)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/builtin_array.go:143 +0x5c8
go.mondoo.com/cnquery/llx.(*blockExecutor).runBoundFunction(0xc003b38310, 0xc004985a10, 0xc004518370, 0x10?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/builtin.go:786 +0x119
go.mondoo.com/cnquery/llx.(*blockExecutor).runFunction(0xc003b38310, 0xc004518370, 0x0?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/llx.go:764 +0xde
go.mondoo.com/cnquery/llx.(*blockExecutor).runChunk(0xc003b38310, 0xc005290b70?, 0x10000000a?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/llx.go:781 +0x248
go.mondoo.com/cnquery/llx.(*blockExecutor).runRef(0xc003b34aa0?, 0x993f4a0?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/llx.go:806 +0xef
go.mondoo.com/cnquery/llx.(*blockExecutor).runChain(0xc003b38310, 0xc005290b40?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/llx.go:838 +0xa6
go.mondoo.com/cnquery/llx.(*blockExecutor).triggerChain(0xc003b38310, 0xc005290b40?, 0xc004985a10)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/llx.go:910 +0x399
go.mondoo.com/cnquery/llx.runResourceFunction.func1({0x8b87c00?, 0xc0044d7de8}, {0x0?, 0x0})
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/builtin.go:735 +0x245
go.mondoo.com/cnquery/resources.(*Runtime).WatchAndUpdate(0xc0041274c0, {0xb557d00, 0xc005903c10}, {0xa2ebf36, 0x4}, {0xc000836b00, 0x31}, 0xc004985980)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/resources/runtime.go:339 +0x37c
go.mondoo.com/cnquery/llx.runResourceFunction(0xc003b38310, 0xc004985920, 0xc00450ddb0, 0x100000008)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/builtin.go:716 +0x22f
go.mondoo.com/cnquery/llx.(*blockExecutor).runBoundFunction(0xc003b38310, 0xc004985920, 0xc00450ddb0, 0xc003a62bc8?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/builtin.go:799 +0xf2
go.mondoo.com/cnquery/llx.(*blockExecutor).runFunction(0xc003b38310, 0xc00450ddb0, 0xc005903c28?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/llx.go:764 +0xde
go.mondoo.com/cnquery/llx.(*blockExecutor).runChunk(0xc003b38310, 0xc005290b70?, 0x100000008?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/llx.go:781 +0x248
go.mondoo.com/cnquery/llx.(*blockExecutor).runRef(0xc003b34aa0?, 0x13?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/llx.go:806 +0xef
go.mondoo.com/cnquery/llx.(*blockExecutor).runChain(0xc003b38310, 0xc005290b40?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/llx.go:838 +0xa6
go.mondoo.com/cnquery/llx.(*blockExecutor).triggerChain(0xc003b38310, 0xa2ee9b6?, 0xc004985920)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/llx.go:910 +0x399
go.mondoo.com/cnquery/llx._resourceWhereV2.func1({0xc003b46b80?, 0x1, 0xc003a12f60?}, {0x58?, 0x93b15a0?, 0xc004a5a750?})
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/builtin_resource.go:99 +0x7ec
go.mondoo.com/cnquery/llx.(*arrayBlockCallResults).update(0xc003b4ca10, 0x0, 0xc000f37ea0)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/llx.go:488 +0x414
go.mondoo.com/cnquery/llx.(*blockExecutor).runFunctionBlocks.func1(0xc000060400?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/llx.go:554 +0x27
go.mondoo.com/cnquery/llx.reportSync.func1(0x907f600?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/llx.go:370 +0xa2
go.mondoo.com/cnquery/llx.(*blockExecutor).triggerChainError(0xc003b4ca80, 0xc004984900?, {0xb4808c0?, 0xc003b47280})
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/llx.go:931 +0x190
go.mondoo.com/cnquery/llx.runResourceFunction.func1({0x8cd1120?, 0x105745e0}, {0xb4808c0?, 0xc003b47280})
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/builtin.go:732 +0x22d
go.mondoo.com/cnquery/resources.(*Runtime).WatchAndUpdate.func1()
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/resources/runtime.go:320 +0x292
go.mondoo.com/cnquery/resources.(*Runtime).WatchAndUpdate(0xc0041274c0, {0xb55a1c0, 0xc005903b50}, {0xc005538aa0, 0x5}, {0xc000836a80, 0x32}, 0xc0049856e0)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/resources/runtime.go:359 +0x44a
go.mondoo.com/cnquery/llx.runResourceFunction(0xc003b4ca80, 0xc004985680, 0xc00450d3b0, 0x400000007)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/builtin.go:716 +0x22f
go.mondoo.com/cnquery/llx.(*blockExecutor).runBoundFunction(0xc003b4ca80, 0xc004985680, 0xc00450d3b0, 0x0?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/builtin.go:799 +0xf2
go.mondoo.com/cnquery/llx.(*blockExecutor).runFunction(0xc003b4ca80, 0xc00450d3b0, 0x0?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/llx.go:764 +0xde
go.mondoo.com/cnquery/llx.(*blockExecutor).runChunk(0xc003b4ca80, 0xc004984930?, 0x400000007?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/llx.go:781 +0x248
go.mondoo.com/cnquery/llx.(*blockExecutor).runRef(0xc003b46b90?, 0xc004984900?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/llx.go:806 +0xef
go.mondoo.com/cnquery/llx.(*blockExecutor).runChain(0xc003b4ca80, 0xc004984900?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/llx.go:838 +0xa6
go.mondoo.com/cnquery/llx.(*blockExecutor).triggerChain(0xc003b4ca80, 0xc004984900?, 0xc004984cf0)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/llx.go:910 +0x399
go.mondoo.com/cnquery/llx.runResourceFunction.func1({0x8cd1120?, 0xc003b34da0}, {0x0?, 0x0})
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/builtin.go:735 +0x245
go.mondoo.com/cnquery/resources.(*Runtime).WatchAndUpdate(0xc0041274c0, {0xb557cc0, 0xc005903710}, {0xc005538a74, 0x3}, {0xc000836900, 0x32}, 0xc004984c90)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/resources/runtime.go:365 +0x4dc
go.mondoo.com/cnquery/llx.runResourceFunction(0xc003b4ca80, 0xc004984810, 0xc00450d1d0, 0x400000003)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/builtin.go:716 +0x22f
go.mondoo.com/cnquery/llx.(*blockExecutor).runBoundFunction(0xc003b4ca80, 0xc004984810, 0xc00450d1d0, 0x0?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/builtin.go:799 +0xf2
go.mondoo.com/cnquery/llx.(*blockExecutor).runFunction(0xc003b4ca80, 0xc00450d1d0, 0xc0030b9da8?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/llx.go:764 +0xde
go.mondoo.com/cnquery/llx.(*blockExecutor).runChunk(0xc003b4ca80, 0xc004984930?, 0x400000003?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/llx.go:781 +0x248
go.mondoo.com/cnquery/llx.(*blockExecutor).runRef(0xc003b46b90?, 0xc004984900?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/llx.go:806 +0xef
go.mondoo.com/cnquery/llx.(*blockExecutor).runChain(0xc003b4ca80, 0xa2f6230?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/llx.go:838 +0xa6
go.mondoo.com/cnquery/llx.(*blockExecutor).run(0xc003b4ca80)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/llx.go:351 +0x2d7
go.mondoo.com/cnquery/llx.(*blockExecutor).runFunctionBlock(0xc003b38310, {0xc005903b20, 0x1, 0xc0038135c0?}, 0x400000000, 0xc0038135c0?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/llx.go:582 +0x12f
go.mondoo.com/cnquery/llx.(*blockExecutor).runFunctionBlocks(0xc003b38310, {0xc0044d7d70, 0x1, 0xa443212?}, 0x0?, 0x8fb5d616cd4dee?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/llx.go:553 +0x11b
go.mondoo.com/cnquery/llx._resourceWhereV2(0xc003b38310, 0xc0049844b0, 0xc00450dd60, 0x100000007, 0x1)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/builtin_resource.go:54 +0x4fd
go.mondoo.com/cnquery/llx.resourceWhereNotV2(0xc00576d950?, 0x6?, 0xa2fd2ee?, 0x9?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/builtin_resource.go:114 +0x1e
go.mondoo.com/cnquery/llx.(*blockExecutor).runBoundFunction(0xc003b38310, 0xc0049844b0, 0xc00450dd60, 0xc?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/builtin.go:786 +0x119
go.mondoo.com/cnquery/llx.(*blockExecutor).runFunction(0xc003b38310, 0xc00450dd60, 0xc000d8d088?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/llx.go:764 +0xde
go.mondoo.com/cnquery/llx.(*blockExecutor).runChunk(0xc003b38310, 0xc005290b70?, 0x100000007?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/llx.go:781 +0x248
go.mondoo.com/cnquery/llx.(*blockExecutor).runRef(0xc003b34aa0?, 0x993f4a0?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/llx.go:806 +0xef
go.mondoo.com/cnquery/llx.(*blockExecutor).runChain(0xc003b38310, 0xc005290b40?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/llx.go:838 +0xa6
go.mondoo.com/cnquery/llx.(*blockExecutor).triggerChain(0xc003b38310, 0xc005290b40?, 0xc004984750)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/llx.go:910 +0x399
go.mondoo.com/cnquery/llx.runResourceFunction.func1({0x8b87c00?, 0xc0044d7d58}, {0x0?, 0x0})
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/builtin.go:735 +0x245
go.mondoo.com/cnquery/resources.(*Runtime).WatchAndUpdate(0xc0041274c0, {0xb557d00, 0xc005903ad8}, {0xa2ebf36, 0x4}, {0xc0008368c0, 0x31}, 0xc0049846c0)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/resources/runtime.go:339 +0x37c
go.mondoo.com/cnquery/llx.runResourceFunction(0xc003b38310, 0xc0049844b0, 0xc00450dd10, 0x100000006)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/builtin.go:716 +0x22f
go.mondoo.com/cnquery/llx.(*blockExecutor).runBoundFunction(0xc003b38310, 0xc0049844b0, 0xc00450dd10, 0x0?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/builtin.go:799 +0xf2
go.mondoo.com/cnquery/llx.(*blockExecutor).runFunction(0xc003b38310, 0xc00450dd10, 0xc0030b9a58?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/llx.go:764 +0xde
go.mondoo.com/cnquery/llx.(*blockExecutor).runChunk(0xc003b38310, 0xc005290b70?, 0x100000006?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/llx.go:781 +0x248
go.mondoo.com/cnquery/llx.(*blockExecutor).runRef(0xc003b34aa0?, 0x13?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/llx.go:806 +0xef
go.mondoo.com/cnquery/llx.(*blockExecutor).runChain(0xc003b38310, 0xc005290b40?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/llx.go:838 +0xa6
go.mondoo.com/cnquery/llx.(*blockExecutor).triggerChain(0xc003b38310, 0xa2ee9b6?, 0xc0049844b0)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/llx.go:910 +0x399
go.mondoo.com/cnquery/llx._resourceWhereV2.func1({0xc003b46440?, 0x1, 0xc0039c6de0?}, {0x58?, 0x100084deba345?, 0x7fd890454990?})
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/builtin_resource.go:99 +0x7ec
go.mondoo.com/cnquery/llx.(*arrayBlockCallResults).update(0xc003b4c7e0, 0x0, 0xc000f37c80)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/llx.go:488 +0x414
go.mondoo.com/cnquery/llx.(*blockExecutor).runFunctionBlocks.func1(0xc000060400?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/llx.go:554 +0x27
go.mondoo.com/cnquery/llx.reportSync.func1(0x907f600?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/llx.go:370 +0xa2
go.mondoo.com/cnquery/llx.runResourceFunction.func1({0x8c0af20?, 0xff995c8}, {0x0?, 0x0})
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/builtin.go:728 +0x20c
go.mondoo.com/cnquery/resources.(*Runtime).WatchAndUpdate.func1()
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/resources/runtime.go:320 +0x292
go.mondoo.com/cnquery/resources.(*Runtime).WatchAndUpdate(0xc0041274c0, {0xb55a180, 0xc005903a58}, {0xc005538a28, 0x6}, {0xc000836700, 0x32}, 0xc00490bf50)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/resources/runtime.go:359 +0x44a
go.mondoo.com/cnquery/llx.runResourceFunction(0xc003b4c850, 0xc00490bef0, 0xc00450cf00, 0x300000006)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/builtin.go:716 +0x22f
go.mondoo.com/cnquery/llx.(*blockExecutor).runBoundFunction(0xc003b4c850, 0xc00490bef0, 0xc00450cf00, 0x0?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/builtin.go:799 +0xf2
go.mondoo.com/cnquery/llx.(*blockExecutor).runFunction(0xc003b4c850, 0xc00450cf00, 0x40fbaa?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/llx.go:764 +0xde
go.mondoo.com/cnquery/llx.(*blockExecutor).runChunk(0xc003b4c850, 0xc00490ba70?, 0x300000006?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/llx.go:781 +0x248
go.mondoo.com/cnquery/llx.(*blockExecutor).runRef(0xc003b46450?, 0xc00490ba40?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/llx.go:806 +0xef
go.mondoo.com/cnquery/llx.(*blockExecutor).runChain(0xc003b4c850, 0xc00490ba40?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/llx.go:838 +0xa6
go.mondoo.com/cnquery/llx.(*blockExecutor).triggerChain(0xc003b4c850, 0xc00490ba40?, 0xc00490bd10)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/llx.go:910 +0x399
go.mondoo.com/cnquery/llx.runResourceFunction.func1({0x8cd1120?, 0xc003b34da0}, {0x0?, 0x0})
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/builtin.go:735 +0x245
go.mondoo.com/cnquery/resources.(*Runtime).WatchAndUpdate(0xc0041274c0, {0xb557cc0, 0xc005903710}, {0xc005538a24, 0x3}, {0xc000836640, 0x32}, 0xc00490bc80)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/resources/runtime.go:365 +0x4dc
go.mondoo.com/cnquery/llx.runResourceFunction(0xc003b4c850, 0xc00490b950, 0xc00450cd70, 0x300000003)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/builtin.go:716 +0x22f
go.mondoo.com/cnquery/llx.(*blockExecutor).runBoundFunction(0xc003b4c850, 0xc00490b950, 0xc00450cd70, 0x300000002?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/builtin.go:799 +0xf2
go.mondoo.com/cnquery/llx.(*blockExecutor).runFunction(0xc003b4c850, 0xc00450cd70, 0xc003b464b0?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/llx.go:764 +0xde
go.mondoo.com/cnquery/llx.(*blockExecutor).runChunk(0xc003b4c850, 0xc00490ba70?, 0x300000003?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/llx.go:781 +0x248
go.mondoo.com/cnquery/llx.(*blockExecutor).runRef(0xc003b46450?, 0xc00490ba40?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/llx.go:806 +0xef
go.mondoo.com/cnquery/llx.(*blockExecutor).runChain(0xc003b4c850, 0xa2f6230?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/llx.go:838 +0xa6
go.mondoo.com/cnquery/llx.(*blockExecutor).run(0xc003b4c850)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/llx.go:351 +0x2d7
go.mondoo.com/cnquery/llx.(*blockExecutor).runFunctionBlock(0xc003b38310, {0xc005903a28, 0x1, 0xc003813500?}, 0x300000000, 0xc003813500?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/llx.go:582 +0x12f
go.mondoo.com/cnquery/llx.(*blockExecutor).runFunctionBlocks(0xc003b38310, {0xc0044d7ce0, 0x1, 0xa443211?}, 0x0?, 0x0?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/llx.go:553 +0x11b
go.mondoo.com/cnquery/llx._resourceWhereV2(0xc003b38310, 0xc00490b740, 0xc00450cfa0, 0x100000005, 0x0)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/builtin_resource.go:54 +0x4fd
go.mondoo.com/cnquery/llx.resourceWhereV2(0xc00576d950?, 0x6?, 0xc005538a10?, 0x5?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/builtin_resource.go:110 +0x1b
go.mondoo.com/cnquery/llx.(*blockExecutor).runBoundFunction(0xc003b38310, 0xc00490b740, 0xc00450cfa0, 0x0?)
        /home/user/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230605211802-0ea753e16e6a/llx/builtin.go:786 +0x119
created by go.mondoo.com/cnspec/policy/executor/internal.(*executionManager).Start
        /home/user/go/src/go.mondoo.io/cnspec/policy/executor/internal/execution_manager.go:54 +0x6a
```

**Comment by chris-rock** [comment]
I am not able to reproduce that behavior with latest cnspec
