### ISSUE TITLE
Mistyping query causes panic but cnspec should error with syntax error instead

### ISSUE THREAD

**Issue by taylormonacelli** [mondoohq/cnspec#662]
**Describe the bug**
Mistyping query causes panic.

**To Reproduce**
```
uname -a
cnspec version
cat <<'EOF' >test.yaml
policies:
- uid: test-policies
  specs:
  - asset_filter:
      query: platform.family.contains(_ == 'unix')
    scoring_queries:
      test: null
queries:
- uid: test
  title: test
  severity: 100
  query: |
    file("/tmp").permissions.mode = 420
EOF
cnspec scan local --policy-bundle test.yaml
```

Oops, i mistyped the == above.

I meant to say:

```
file("/tmp").permissions.mode == 420
```

**Expected behavior**
If this assignment is invalid, cnspec should error with friendly message.

**Screenshots or CLI Output**

```
[mtm@taylors-MacBook-Pro-2:tmp]$ uname -a
cnspec version
cat <<'EOF' >test.yaml
policies:
- uid: test-policies
  specs:
  - asset_filter:
      query: platform.family.contains(_ == 'unix')
    scoring_queries:
      test: null
queries:
- uid: test
  title: test
  severity: 100
  query: |
    file("/tmp").permissions.mode = 420
EOF
cnspec scan local --policy-bundle test.yaml
Darwin taylors-MacBook-Pro-2.local 21.6.0 Darwin Kernel Version 21.6.0: Thu Jun  8 23:57:12 PDT 2023; root:xnu-8020.240.18.701.6~1/RELEASE_X86_64 x86_64 i386 Darwin
cnspec 8.18.0 (c76f6a9, 2023-07-11T10:52:06Z)
→ no Mondoo configuration file provided. using defaults
→ discover related assets for 1 asset(s)
→ resolved assets resolved-assets=1
panic: no callback points

goroutine 44 [running]:
go.mondoo.com/cnquery/llx.(*MQLExecutorV2)._newBlockExecutor(0xc00366f810, 0xd0e78fc22d3fe6b9?, 0xc003662bd0, 0x0)
        /home/runner/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230711094059-d4b66ec651d9/llx/llx.go:227 +0x745
go.mondoo.com/cnquery/llx.NewExecutorV2(0xc0035c39e0, 0xc003376800, 0xc00368e750, 0xc0035b9310?)
        /home/runner/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230711094059-d4b66ec651d9/llx/llx.go:166 +0x17b
go.mondoo.com/cnspec/policy/executor/internal.(*executionManager).executeCodeBundle(0xc000a174a0, 0xc00363c140, 0xc000dec840?, {0x0, 0x0})
        /home/runner/_work/cnspec/cnspec/policy/executor/internal/execution_manager.go:162 +0x4fe
go.mondoo.com/cnspec/policy/executor/internal.(*executionManager).Start.func1()
        /home/runner/_work/cnspec/cnspec/policy/executor/internal/execution_manager.go:85 +0x1cb
created by go.mondoo.com/cnspec/policy/executor/internal.(*executionManager).Start
        /home/runner/_work/cnspec/cnspec/policy/executor/internal/execution_manager.go:54 +0x6a
[mtm@taylors-MacBook-Pro-2:tmp]$
```

**Comment by mariuskimmina** [comment]
Linking related issue on cnquery: https://github.com/mondoohq/cnquery/issues/1227

**Comment by taylormonacelli** [comment]
Thanks for the link.  I'll follow it there.
