### ISSUE TITLE
Panic in cnspec when scanning

### ISSUE THREAD

**Issue by tas50** [mondoohq/cnspec#665]
**Describe the bug**
Panic in cnspec when scanning my raspi system.

```
→ no provider specified, defaulting to local.
  Use --help for a list of available providers.
→ loaded configuration from /etc/opt/mondoo/mondoo.yml using source default
DBG parsing asset asset-type=1 provider=LOCAL_OS
DBG initialize client authentication issuer=mondoo/ams kid=//agents.api.mondoo.app/spaces/beautiful-wiles-231755/serviceaccounts/2T7UbHwOt3FOqu1lk7NcbDzNVVI
DBG local> run command uname -s
DBG local> run command uname -m
DBG platform> cannot parse lsb config on this linux system error="open /etc/lsb-release: no such file or directory"
DBG local> run command uname -m
DBG platform> detected os family=["debian","linux","unix","os"] platform=raspbian
DBG local> run command hostname
DBG local> run command hostname
→ using service account credentials
→ discover related assets for 1 asset(s)
DBG run resolver resolver="Local Resolver" resolver-id=local
DBG establish motor connection
DBG connection> load local provider
DBG local> run command hostname
DBG unable to read /sys/class/dmi/id/sys_vendor error="open /sys/class/dmi/id/sys_vendor: no such file or directory"
DBG unable to read /sys/class/dmi/id/product_version error="open /sys/class/dmi/id/product_version: no such file or directory"
DBG unable to read /sys/class/dmi/id/product_name error="open /sys/class/dmi/id/product_name: no such file or directory"
DBG unable to read /sys/class/dmi/id/bios_vendor error="open /sys/class/dmi/id/bios_vendor: no such file or directory"
DBG detected platform ids id-detector=["hostname","cloud-detect"] platform-ids=["//platformid.api.mondoo.app/hostname/adsbexchange"]
DBG local> run command hostname
→ resolved assets resolved-assets=1
DBG connecting to asset adsbexchange (baremetal)
DBG using API endpoint https://us.api.mondoo.com
DBG establish connection to asset connection=local insecure=false
DBG establish motor connection
DBG connection> load local provider
DBG established connection
DBG update asset asset=adsbexchange platform-ids=["//platformid.api.mondoo.app/hostname/adsbexchange"]
DBG using API endpoint https://us.api.mondoo.com
DBG run scan asset=adsbexchange
DBG client> request policies bundle for asset asset=//assets.api.mondoo.app/spaces/beautiful-wiles-231755/assets/2T7UbpunaI25Jp9fA98iTEitF1i
DBG marketplace> fetch policy bundle from upstream policy=//assets.api.mondoo.app/spaces/beautiful-wiles-231755/assets/2T7UbpunaI25Jp9fA98iTEitF1i req-id=global
DBG store policy mrn=//policy.api.mondoo.app/policies/github-benchmark-level-2 owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/github-benchmark-level-2
DBG store policy mrn=//policy.api.mondoo.app/policies/mondoo-github-repository-best-practices owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/mondoo-github-repository-best-practices
DBG store policy mrn=//policy.api.mondoo.app/policies/mondoo-vmware-vsphere-esxi-security-baseline owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/mondoo-vmware-vsphere-esxi-security-baseline
DBG store policy mrn=//policy.api.mondoo.app/policies/mondoo-vmware-vsphere-security-baseline owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/mondoo-vmware-vsphere-security-baseline
DBG store policy mrn=//policy.api.mondoo.app/spaces/beautiful-wiles-231755/policies/aws-security-v2 owner=//captain.api.mondoo.app/spaces/beautiful-wiles-231755 req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/spaces/beautiful-wiles-231755/policies/aws-security-v2
DBG store policy mrn=//policy.api.mondoo.app/spaces/beautiful-wiles-231755/policies/mondoo-google-cloud-storage-best-practices owner=//captain.api.mondoo.app/spaces/beautiful-wiles-231755 req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/spaces/beautiful-wiles-231755/policies/mondoo-google-cloud-storage-best-practices
DBG store policy mrn=//policy.api.mondoo.app/policies/almalinux-9-level-1-server owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/almalinux-9-level-1-server
DBG store policy mrn=//policy.api.mondoo.app/policies/mondoo-asset-inventory-aws owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/mondoo-asset-inventory-aws
DBG store policy mrn=//policy.api.mondoo.app/policies/mondoo-google-workspace-security owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/mondoo-google-workspace-security
DBG store policy mrn=//policy.api.mondoo.app/policies/mondoo-macos-security owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/mondoo-macos-security
DBG store policy mrn=//policy.api.mondoo.app/policies/rocky-linux-8-level-1-server owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/rocky-linux-8-level-1-server
DBG store policy mrn=//policy.api.mondoo.app/policies/cis-google-gke-level-1 owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/cis-google-gke-level-1
DBG store policy mrn=//policy.api.mondoo.app/policies/mondoo-kubernetes-security owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/mondoo-kubernetes-security
DBG store policy mrn=//policy.api.mondoo.app/policies/mondoo-linux-security owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/mondoo-linux-security
DBG store policy mrn=//policy.api.mondoo.app/policies/mondoo-windows-asset-inventory owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/mondoo-windows-asset-inventory
DBG store policy mrn=//policy.api.mondoo.app/policies/oracle-linux-7-level-1-server owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/oracle-linux-7-level-1-server
DBG store policy mrn=//policy.api.mondoo.app/policies/mondoo-kubernetes-best-practices owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/mondoo-kubernetes-best-practices
DBG store policy mrn=//policy.api.mondoo.app/policies/microsoft-365-foundations-e3-level-2 owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/microsoft-365-foundations-e3-level-2
DBG store policy mrn=//policy.api.mondoo.app/policies/rocky-linux-9-level-1-server owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/rocky-linux-9-level-1-server
DBG store policy mrn=//policy.api.mondoo.app/policies/ubuntu-1404-level-1-server owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/ubuntu-1404-level-1-server
DBG store policy mrn=//policy.api.mondoo.app/spaces/beautiful-wiles-231755/policies/mondoo-google-cloud-storage-security owner=//captain.api.mondoo.app/spaces/beautiful-wiles-231755 req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/spaces/beautiful-wiles-231755/policies/mondoo-google-cloud-storage-security
DBG store policy mrn=//policy.api.mondoo.app/policies/almalinux-8-level-1-server owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/almalinux-8-level-1-server
DBG store policy mrn=//policy.api.mondoo.app/policies/mondoo-asset-inventory-gcp owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/mondoo-asset-inventory-gcp
DBG store policy mrn=//policy.api.mondoo.app/policies/mondoo-gitlab-security owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/mondoo-gitlab-security
DBG store policy mrn=//policy.api.mondoo.app/policies/mondoo-kubernetes-inventory owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/mondoo-kubernetes-inventory
DBG store policy mrn=//policy.api.mondoo.app/policies/platform-vulnerability owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/platform-vulnerability
DBG store policy mrn=//policy.api.mondoo.app/policies/cis-azure-aks-level-1 owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/cis-azure-aks-level-1
DBG store policy mrn=//policy.api.mondoo.app/policies/asset-overview owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/asset-overview
DBG store policy mrn=//policy.api.mondoo.app/policies/cis-apple-macos-13-benchmark-l1 owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/cis-apple-macos-13-benchmark-l1
DBG store policy mrn=//policy.api.mondoo.app/policies/debian-11-level-1-server owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/debian-11-level-1-server
DBG store policy mrn=//policy.api.mondoo.app/policies/microsoft-azure-foundations-level-1 owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/microsoft-azure-foundations-level-1
DBG store policy mrn=//policy.api.mondoo.app/policies/mondoo-slack-security owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/mondoo-slack-security
DBG store policy mrn=//policy.api.mondoo.app/policies/rhel-7-level-1-server owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/rhel-7-level-1-server
DBG store policy mrn=//policy.api.mondoo.app/spaces/beautiful-wiles-231755/policies/oracle-cloud-infrastructure-level-1 owner=//captain.api.mondoo.app/spaces/beautiful-wiles-231755 req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/spaces/beautiful-wiles-231755/policies/oracle-cloud-infrastructure-level-1
DBG store policy mrn=//policy.api.mondoo.app/policies/amazon-web-services-foundations-level-1 owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/amazon-web-services-foundations-level-1
DBG store policy mrn=//policy.api.mondoo.app/policies/mondoo-github-organization-security-level-1 owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/mondoo-github-organization-security-level-1
DBG store policy mrn=//policy.api.mondoo.app/policies/rhel-6-level-1-server owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/rhel-6-level-1-server
DBG store policy mrn=//policy.api.mondoo.app/policies/amazon-web-services-operational-best-practices-for-nist-800-171 owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/amazon-web-services-operational-best-practices-for-nist-800-171
DBG store policy mrn=//policy.api.mondoo.app/policies/mondoo-okta-security owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/mondoo-okta-security
DBG store policy mrn=//policy.api.mondoo.app/policies/sles-11-level-1-server owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/sles-11-level-1-server
DBG store policy mrn=//policy.api.mondoo.app/policies/amazon-linux-2-level-1 owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/amazon-linux-2-level-1
DBG store policy mrn=//policy.api.mondoo.app/policies/amazon-web-services-foundations-level-2 owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/amazon-web-services-foundations-level-2
DBG store policy mrn=//policy.api.mondoo.app/policies/amazon-web-services-operational-best-practices-for-nist-1800-25 owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/amazon-web-services-operational-best-practices-for-nist-1800-25
DBG store policy mrn=//policy.api.mondoo.app/policies/bsi-sys12-windows-server owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/bsi-sys12-windows-server
DBG store policy mrn=//policy.api.mondoo.app/policies/cis-amazon-eks-level-1 owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/cis-amazon-eks-level-1
DBG store policy mrn=//policy.api.mondoo.app/policies/cis-apple-macos-11-0-benchmark-l1 owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/cis-apple-macos-11-0-benchmark-l1
DBG store policy mrn=//policy.api.mondoo.app/policies/cis-apple-macos-12-benchmark-l1 owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/cis-apple-macos-12-benchmark-l1
DBG store policy mrn=//policy.api.mondoo.app/policies/cis-azure-aks-level-2 owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/cis-azure-aks-level-2
DBG store policy mrn=//policy.api.mondoo.app/policies/cis-oracle-linux-9-benchmark-l1-server owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/cis-oracle-linux-9-benchmark-l1-server
DBG store policy mrn=//policy.api.mondoo.app/policies/debian-10-level-1-server owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/debian-10-level-1-server
DBG store policy mrn=//policy.api.mondoo.app/policies/debian-8-level-1-server owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/debian-8-level-1-server
DBG store policy mrn=//policy.api.mondoo.app/policies/debian-9-level-1-server owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/debian-9-level-1-server
DBG store policy mrn=//policy.api.mondoo.app/policies/google-cloud-platform-foundation-level-1 owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/google-cloud-platform-foundation-level-1
DBG store policy mrn=//policy.api.mondoo.app/policies/microsoft-365-foundations-e3-level-1 owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/microsoft-365-foundations-e3-level-1
DBG store policy mrn=//policy.api.mondoo.app/policies/microsoft-azure-foundations-level-2 owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/microsoft-azure-foundations-level-2
DBG store policy mrn=//policy.api.mondoo.app/policies/mondoo-asset-inventory-azure owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/mondoo-asset-inventory-azure
DBG store policy mrn=//policy.api.mondoo.app/policies/mondoo-gcp-security owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/mondoo-gcp-security
DBG store policy mrn=//policy.api.mondoo.app/policies/mondoo-github-inventory-org owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/mondoo-github-inventory-org
DBG store policy mrn=//policy.api.mondoo.app/policies/mondoo-googleworkspace-incident-response owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/mondoo-googleworkspace-incident-response
DBG store policy mrn=//policy.api.mondoo.app/policies/mondoo-incident-response-aws owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/mondoo-incident-response-aws
DBG store policy mrn=//policy.api.mondoo.app/policies/mondoo-linux-inventory owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/mondoo-linux-inventory
DBG store policy mrn=//policy.api.mondoo.app/policies/mondoo-macos-inventory owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/mondoo-macos-inventory
DBG store policy mrn=//policy.api.mondoo.app/policies/mondoo-okta-incident-response owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/mondoo-okta-incident-response
DBG store policy mrn=//policy.api.mondoo.app/policies/mondoo-slack-incident-response owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/mondoo-slack-incident-response
DBG store policy mrn=//policy.api.mondoo.app/policies/mondoo-windows-security owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/mondoo-windows-security
DBG store policy mrn=//policy.api.mondoo.app/policies/platform-eol owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/platform-eol
DBG store policy mrn=//policy.api.mondoo.app/policies/rhel-8-level-1-server owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/rhel-8-level-1-server
DBG store policy mrn=//policy.api.mondoo.app/policies/rhel-9-level-1-server owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/rhel-9-level-1-server
DBG store policy mrn=//policy.api.mondoo.app/policies/ubuntu-1604-level-1-server owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/ubuntu-1604-level-1-server
DBG store policy mrn=//policy.api.mondoo.app/policies/ubuntu-1804-level-1-server owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/ubuntu-1804-level-1-server
DBG store policy mrn=//policy.api.mondoo.app/policies/ubuntu-2004-level-1-server owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/ubuntu-2004-level-1-server
DBG store policy mrn=//policy.api.mondoo.app/policies/ubuntu-2204-level-1-server owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/ubuntu-2204-level-1-server
DBG store policy mrn=//policy.api.mondoo.app/policies/windows-server-2016-l1-ms owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/windows-server-2016-l1-ms
DBG store policy mrn=//policy.api.mondoo.app/policies/windows-server-2019-l1-ms owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/windows-server-2019-l1-ms
DBG store policy mrn=//policy.api.mondoo.app/policies/windows-server-2022-l1-ms owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/policies/windows-server-2022-l1-ms
DBG store policy mrn=//policy.api.mondoo.app/spaces/beautiful-wiles-231755/policies/mondoo-gcp-storage-security owner=//captain.api.mondoo.app/spaces/beautiful-wiles-231755 req-id=global uid=
DBG invalidate policy cache policy=//policy.api.mondoo.app/spaces/beautiful-wiles-231755/policies/mondoo-gcp-storage-security
DBG store policy mrn=//captain.api.mondoo.app/spaces/beautiful-wiles-231755 owner=//policy.api.mondoo.app req-id=global uid=
DBG invalidate policy cache policy=//captain.api.mondoo.app/spaces/beautiful-wiles-231755
DBG store policy mrn=//assets.api.mondoo.app/spaces/beautiful-wiles-231755/assets/2T7UbpunaI25Jp9fA98iTEitF1i owner=//captain.api.mondoo.app/spaces/beautiful-wiles-231755 req-id=global uid=
DBG invalidate policy cache policy=//assets.api.mondoo.app/spaces/beautiful-wiles-231755/assets/2T7UbpunaI25Jp9fA98iTEitF1i
DBG marketplace> fetched policy bundle from upstream policy=//assets.api.mondoo.app/spaces/beautiful-wiles-231755/assets/2T7UbpunaI25Jp9fA98iTEitF1i req-id=global
DBG client> got policy bundle
DBG client> got policy filters asset=//assets.api.mondoo.app/spaces/beautiful-wiles-231755/assets/2T7UbpunaI25Jp9fA98iTEitF1i
panic: cannot compute checksum for chunk, it doesn't seem to reference a function on the stack

goroutine 51 [running]:
go.mondoo.com/cnquery/llx.(*Function).checksumV2(0x15123140, 0x15122870)
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230725090200-9e647075afc8/llx/chunk.go:115 +0x26c
go.mondoo.com/cnquery/llx.(*Chunk).ChecksumV2(0x15123110, 0x1, 0x15122870)
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230725090200-9e647075afc8/llx/chunk.go:102 +0x1d0
go.mondoo.com/cnquery/llx.(*Block).AddChunk(0x151009c0, 0x15122870, 0x1, 0x15123110)
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230725090200-9e647075afc8/llx/code.go:54 +0x44
go.mondoo.com/cnquery/mqlc.(*compiler).addValueFieldChunks.func2(0x1505d910, {0x14ff9a00, 0x1, 0x10}, 0x1, 0x151009c0, 0x15122c90)
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230725090200-9e647075afc8/mqlc/mqlc.go:1820 +0x464
go.mondoo.com/cnquery/mqlc.(*compiler).addValueFieldChunks.func6(0x1505d8f0, 0x150eb1a0, {0x14ff9a00, 0x1, 0x10})
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230725090200-9e647075afc8/mqlc/mqlc.go:1877 +0x68
go.mondoo.com/cnquery/mqlc.(*compiler).addValueFieldChunks.func3(0x1505d8f0, 0x150eb188, {0x14ff9a00, 0x0, 0x10}, 0x150eb200)
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230725090200-9e647075afc8/mqlc/mqlc.go:1832 +0x134
go.mondoo.com/cnquery/mqlc.(*compiler).addValueFieldChunks(0x1291a910, 0x100000006)
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230725090200-9e647075afc8/mqlc/mqlc.go:1875 +0x4b0
go.mondoo.com/cnquery/mqlc.(*compiler).postCompile(0x1291a910)
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230725090200-9e647075afc8/mqlc/mqlc.go:1708 +0x348
go.mondoo.com/cnquery/mqlc.(*compiler).CompileParsed(0x1291a910, 0x1505d650)
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230725090200-9e647075afc8/mqlc/mqlc.go:2075 +0x58
go.mondoo.com/cnquery/mqlc.CompileAST(0x1505d650, 0x0, {0x10963068, 0x0})
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230725090200-9e647075afc8/mqlc/mqlc.go:2144 +0x3ec
go.mondoo.com/cnquery/mqlc.compile({0x124f5800, 0x53}, 0x0, {0x10963068, 0x0})
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230725090200-9e647075afc8/mqlc/mqlc.go:2165 +0x80
go.mondoo.com/cnquery/mqlc.Compile({0x124f5800, 0x53}, 0x0, {0x10963068, 0x0})
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230725090200-9e647075afc8/mqlc/mqlc.go:2191 +0x3c
go.mondoo.com/cnspec/policy/executor.ExecuteFilterQueries(0x10963068, 0x1044e6a0, {0x1488dc00, 0xda, 0xda}, 0x12a05f200)
	/home/runner/_work/cnspec/cnspec/policy/executor/graph.go:53 +0x10c
go.mondoo.com/cnspec/policy/scan.(*localAssetScanner).FilterQueries(...)
	/home/runner/_work/cnspec/cnspec/policy/scan/local_scanner.go:877
go.mondoo.com/cnspec/policy/scan.(*localAssetScanner).UpdateFilters(0xf89ddf8, 0xf89dd54, 0x12a05f200)
	/home/runner/_work/cnspec/cnspec/policy/scan/local_scanner.go:883 +0x58
go.mondoo.com/cnspec/policy/scan.(*localAssetScanner).runPolicy(0xf89ddf8)
	/home/runner/_work/cnspec/cnspec/policy/scan/local_scanner.go:819 +0x2c8
go.mondoo.com/cnspec/policy/scan.(*localAssetScanner).run(0xf89ddf8)
	/home/runner/_work/cnspec/cnspec/policy/scan/local_scanner.go:625 +0x3c
go.mondoo.com/cnspec/policy/scan.(*LocalScanner).runMotorizedAsset.func1(0x1044e540, 0xf80de60)
	/home/runner/_work/cnspec/cnspec/policy/scan/local_scanner.go:454 +0x4cc
go.mondoo.com/cnspec/internal/datalakes/inmemory.WithDb(0x104e7a00, 0x106a3e84)
	/home/runner/_work/cnspec/cnspec/internal/datalakes/inmemory/inmemory.go:48 +0x58
go.mondoo.com/cnspec/policy/scan.(*LocalScanner).runMotorizedAsset(0x102df040, 0xfef21c0)
	/home/runner/_work/cnspec/cnspec/policy/scan/local_scanner.go:428 +0x70
go.mondoo.com/cnspec/policy/scan.(*LocalScanner).RunAssetJob.func1(0xfef21c0, 0x10605f3c, 0x102df040, 0xf96cf60)
	/home/runner/_work/cnspec/cnspec/policy/scan/local_scanner.go:400 +0x4f4
go.mondoo.com/cnspec/policy/scan.(*LocalScanner).RunAssetJob(0x102df040, 0xfef21c0)
	/home/runner/_work/cnspec/cnspec/policy/scan/local_scanner.go:414 +0x4b0
go.mondoo.com/cnspec/policy/scan.(*LocalScanner).distributeJob.func1()
	/home/runner/_work/cnspec/cnspec/policy/scan/local_scanner.go:294 +0xd8
created by go.mondoo.com/cnspec/policy/scan.(*LocalScanner).distributeJob
	/home/runner/_work/cnspec/cnspec/policy/scan/local_scanner.go:277 +0xc4c
root@adsbexchange:/home/pi#
```

**Comment by tas50** [comment]
This is not occuring in 8.21
