### ISSUE TITLE
V9: Panic running `cnspec scan github org` without an org

### ISSUE THREAD

**Issue by tas50** [mondoohq/cnspec#745]
**Describe the bug**
When incorrectly formatting the scan CLI, cnspec panics instead of throwing an error with V9 beta 3:

```
tsmith@timnas:~$ ./cnspec scan github org --token foo
panic: runtime error: index out of range [1] with length 1

goroutine 27 [running]:
go.mondoo.com/cnquery/providers/github/provider.(*Service).ParseCLI(0xd48e20?, 0xc000322480)
	/home/runner/_work/cnquery/cnquery/providers/github/provider/provider.go:78 +0x7b2
go.mondoo.com/cnquery/providers-sdk/v1/plugin.(*GRPCServer).ParseCLI(0xd5d040?, {0xc000322480?, 0x4c41a6?}, 0x0?)
	/home/runner/_work/cnquery/cnquery/providers-sdk/v1/plugin/grpc.go:79 +0x1e
go.mondoo.com/cnquery/providers-sdk/v1/plugin._ProviderPlugin_ParseCLI_Handler({0xd48e20?, 0xc00013d2e0}, {0xf17220, 0xc000318510}, 0xc000352000, 0x0)
	/home/runner/_work/cnquery/cnquery/providers-sdk/v1/plugin/plugin_grpc.pb.go:161 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00022e1e0, {0xf1b098, 0xc0003024e0}, 0xc000241680, 0xc0002e84e0, 0x15440c0, 0x0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.58.1/server.go:1376 +0xde7
google.golang.org/grpc.(*Server).handleStream(0xc00022e1e0, {0xf1b098, 0xc0003024e0}, 0xc000241680, 0x0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.58.1/server.go:1753 +0x9e7
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.58.1/server.go:998 +0x8d
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 36
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.58.1/server.go:996 +0x165
x failed to shutdown the provider error="rpc error: code = Unavailable desc = connection error: desc = \"transport: error while dialing: dial unix /tmp/plugin1956633544: connect: connection refused\""
FTL failed to parse cli arguments error="rpc error: code = Unavailable desc = error reading from server: EOF"
```

**Comment by vjeffrey** [comment]
this appears to be fixed now
