### ISSUE TITLE
`vuln` command not migrated to v9

### ISSUE THREAD

**Issue by czunker** [mondoohq/cnspec#754]
**Describe the bug**
```
cnspec-v9 vuln container image alpine:3.8.4 --config ~/workspace/mondoo/sa-edge-default.json
! CLI pre-processing encountered an issue error="unknown flag: --config"
panic: NOT YET MIGRATED

goroutine 1 [running]:
go.mondoo.com/cnspec/apps/cnspec/cmd.glob..func21(0xc0008dc800?, {0x157d5da?, 0x4?, 0x157d58a?})
	/home/runner/_work/cnspec/cnspec/apps/cnspec/cmd/vuln.go:18 +0x25
github.com/spf13/cobra.(*Command).execute(0x2248c80, {0xc0006939a0, 0x5, 0x5})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x863
github.com/spf13/cobra.(*Command).ExecuteC(0x2247b40)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
go.mondoo.com/cnspec/apps/cnspec/cmd.Execute()
	/home/runner/_work/cnspec/cnspec/apps/cnspec/cmd/root.go:109 +0x19b
main.main()
	/home/runner/_work/cnspec/cnspec/apps/cnspec/cnspec.go:9 +0xf
```

**Expected behavior**
`vuln` command should work.

**Comment by vjeffrey** [comment]
branch with this work is pushed up, will pr in the morning

**Comment by vjeffrey** [comment]
https://github.com/mondoohq/cnspec/pull/791
