### ISSUE TITLE
`incognito` scan isn't working in v9

### ISSUE THREAD

**Issue by czunker** [mondoohq/cnspec#755]
**Describe the bug**
```
cnspec scan container image alpine:3.8.4 --config ~/workspace/mondoo/sa-edge-default.json --incognito
! CLI pre-processing encountered an issue error="unknown flag: --config"
→ loaded configuration from /home/christian/workspace/mondoo/sa-edge-default.json using source --config
→ discover related assets for 1 asset(s)
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
go.mondoo.com/cnspec/policy/scan.(*LocalScanner).distributeJob(0xc0001ec9a0, 0xc0001eca10, {0x17af6f0, 0xc000c911a0}, 0xc0001eca80)
	/home/christian/workspace/mondoo/github.com/cnspec/policy/scan/local_scanner.go:367 +0x17e6
go.mondoo.com/cnspec/policy/scan.(*LocalScanner).RunIncognito(0x17af6b8?, {0x17af6f0, 0xc000c911a0}, 0xc0001eca10)
	/home/christian/workspace/mondoo/github.com/cnspec/policy/scan/local_scanner.go:180 +0x7b
go.mondoo.com/cnspec/apps/cnspec/cmd.RunScan(0xc000a63180, {0x0?, 0xc000b1e660?, 0x17af6b8?})
	/home/christian/workspace/mondoo/github.com/cnspec/apps/cnspec/cmd/scan.go:285 +0x305
go.mondoo.com/cnspec/apps/cnspec/cmd.glob..func13(0x0?, 0x17b04d0?, 0x22ad800?)
	/home/christian/workspace/mondoo/github.com/cnspec/apps/cnspec/cmd/scan.go:120 +0xaf
go.mondoo.com/cnquery/cli/providers.setConnector.func2(0xc0006de800?, {0xc00035dae0?, 0x2, 0x5})
	/home/christian/workspace/mondoo/github.com/cnquery/cli/providers/providers.go:446 +0x8c3
github.com/spf13/cobra.(*Command).execute(0xc0006c7200, {0xc00035da90, 0x5, 0x5})
	/home/christian/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x863
github.com/spf13/cobra.(*Command).ExecuteC(0x2263e60)
	/home/christian/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
	/home/christian/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
go.mondoo.com/cnspec/apps/cnspec/cmd.Execute()
	/home/christian/workspace/mondoo/github.com/cnspec/apps/cnspec/cmd/root.go:109 +0x19b
main.main()
	/home/christian/workspace/mondoo/github.com/cnspec/apps/cnspec/cnspec.go:9 +0xf
```

**Expected behavior**
I'd expect the scan to work without reporting results upstream.

**Additional context**
Using no config has the same outcome:
```
cnspec scan container image alpine:3.8.4 --config /dev/null 
! CLI pre-processing encountered an issue error="unknown flag: --config"
→ loaded configuration from /dev/null using source --config
! No credentials provided. Switching to --incognito mode.
→ discover related assets for 1 asset(s)
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
go.mondoo.com/cnspec/policy/scan.(*LocalScanner).distributeJob(0xc000720cb0, 0xc000720e00, {0x17af6f0, 0xc000bfc690}, 0xc000720e70)
	/home/christian/workspace/mondoo/github.com/cnspec/policy/scan/local_scanner.go:367 +0x17e6
go.mondoo.com/cnspec/policy/scan.(*LocalScanner).RunIncognito(0x17af6b8?, {0x17af6f0, 0xc000bfc690}, 0xc000720e00)
	/home/christian/workspace/mondoo/github.com/cnspec/policy/scan/local_scanner.go:180 +0x7b
go.mondoo.com/cnspec/apps/cnspec/cmd.RunScan(0xc000927360, {0x0?, 0xc000d781b0?, 0x17af6b8?})
	/home/christian/workspace/mondoo/github.com/cnspec/apps/cnspec/cmd/scan.go:285 +0x305
go.mondoo.com/cnspec/apps/cnspec/cmd.glob..func13(0x0?, 0x17b04d0?, 0x22ad800?)
	/home/christian/workspace/mondoo/github.com/cnspec/apps/cnspec/cmd/scan.go:120 +0xaf
go.mondoo.com/cnquery/cli/providers.setConnector.func2(0xc000b83400?, {0xc00025b340?, 0x2, 0x4})
	/home/christian/workspace/mondoo/github.com/cnquery/cli/providers/providers.go:446 +0x8c3
github.com/spf13/cobra.(*Command).execute(0xc00098a600, {0xc00025b300, 0x4, 0x4})
	/home/christian/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x863
github.com/spf13/cobra.(*Command).ExecuteC(0x2263e60)
	/home/christian/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
	/home/christian/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
go.mondoo.com/cnspec/apps/cnspec/cmd.Execute()
	/home/christian/workspace/mondoo/github.com/cnspec/apps/cnspec/cmd/root.go:109 +0x19b
main.main()
	/home/christian/workspace/mondoo/github.com/cnspec/apps/cnspec/cnspec.go:9 +0xf
```

**Comment by vjeffrey** [comment]
looks like this is resolved now
