### ISSUE TITLE
scan running container panics in azure discovery

### ISSUE THREAD

**Issue by czunker** [mondoohq/cnspec#758]
**Describe the bug**
```
cnspec-v9 scan container bc7fbc466c7c --config ~/workspace/mondoo/sa-prod-us-default.json                                                             
! CLI pre-processing encountered an issue error="unknown flag: --config"
→ loaded configuration from /home/christian/workspace/mondoo/sa-prod-us-default.json using source --config
→ using service account credentials
→ discover related assets for 1 asset(s)
→ synchronize assets

 musing_hermann ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────   0%


panic: assignment to entry in nil map

goroutine 16 [running]:
go.mondoo.com/cnquery/providers/azure/resources.getSubConfig(0x0?, {0xc0005841e0, {0x184e700, 0x0, 0x0}, 0xc000012600, 0xc00058a180, 0xc0005841d0, 0xc000584160, 0xc0005840f0, ...})
	/home/christian/workspace/mondoo/github.com/cnquery/providers/azure/resources/discovery.go:643 +0x85
go.mondoo.com/cnquery/providers/azure/resources.Discover(0xc00043ed80, 0xc0001de780)
	/home/christian/workspace/mondoo/github.com/cnquery/providers/azure/resources/discovery.go:87 +0x2f8
go.mondoo.com/cnquery/providers/azure/provider.(*Service).discover(0xc0001f1870?, 0xc000257bc0, 0x1137b98?)
	/home/christian/workspace/mondoo/github.com/cnquery/providers/azure/provider/provider.go:281 +0xe5
go.mondoo.com/cnquery/providers/azure/provider.(*Service).Connect(0xc0002ee100?, 0xc0000996e0, {0x1137b98?, 0xc000433310?})
	/home/christian/workspace/mondoo/github.com/cnquery/providers/azure/provider/provider.go:132 +0x6f
go.mondoo.com/cnquery/providers-sdk/v1/plugin.(*GRPCServer).Connect(0xc000037cc0, {0xc0000996e0?, 0x4cc226?}, 0xc0000996e0)
	/home/christian/workspace/mondoo/github.com/cnquery/providers-sdk/v1/plugin/grpc.go:92 +0xd5
go.mondoo.com/cnquery/providers-sdk/v1/plugin._ProviderPlugin_Connect_Handler({0xf251c0?, 0xc000037cc0}, {0x113a3c0, 0xc00041c000}, 0xc0002d6bd0, 0x0)
	/home/christian/workspace/mondoo/github.com/cnquery/providers-sdk/v1/plugin/plugin_grpc.pb.go:179 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002401e0, {0x113f178, 0xc00024d6c0}, 0xc000249c20, 0xc000287710, 0x180e678, 0x0)
	/home/christian/go/pkg/mod/google.golang.org/grpc@v1.58.1/server.go:1376 +0xde7
google.golang.org/grpc.(*Server).handleStream(0xc0002401e0, {0x113f178, 0xc00024d6c0}, 0xc000249c20, 0x0)
	/home/christian/go/pkg/mod/google.golang.org/grpc@v1.58.1/server.go:1753 +0x9e7

 musing_hermann ━━───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────   1%
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 12
	/home/christian/go/pkg/mod/google.golang.org/grpc@v1.58.1/server.go:996 +0x165
```

The image for this container is a alpine based nginx. This shouldn't trigger azure discovery at all.

**To Reproduce**

1. Run container with image `nginx:alpine`
2. Run above command against the container
3. Note the error

**Expected behavior**
No azure discovery, no panic.

**Desktop (please complete the following information):**

- cnspec beta4

**Comment by czunker** [comment]
Also happended with an Ubuntu based container.

**Comment by czunker** [comment]
This still happens with cnquery beta7:
```
cnquery scan container bc7fbc466c7c --config ~/workspace/mondoo/sa-prod-us-default.json                                                                                                                                                          ✔ │ 14:23:02 
! CLI pre-processing encountered an issue error="unknown flag: --config"
→ loaded configuration from /home/christian/workspace/mondoo/sa-prod-us-default.json using source --config
→ using service account credentials
→ discover related assets for 1 asset(s)
→ synchronize assets

 musing_hermann ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────   0%


panic: assignment to entry in nil map

goroutine 50 [running]:
go.mondoo.com/cnquery/providers/azure/resources.getSubConfig(0x0?, {0xc00004ce00, {0x184e700, 0x0, 0x0}, 0xc00052a180, 0xc0005d6060, 0xc00004c170, 0xc00004cdf0, 0xc00004cd50, ...})
	/home/christian/workspace/mondoo/github.com/cnquery/providers/azure/resources/discovery.go:643 +0x85
go.mondoo.com/cnquery/providers/azure/resources.Discover(0xc0003819e0, 0xc0003ba4b0)
	/home/christian/workspace/mondoo/github.com/cnquery/providers/azure/resources/discovery.go:87 +0x2f8
go.mondoo.com/cnquery/providers/azure/provider.(*Service).discover(0xc0001f1870?, 0xc00039cd00, 0x1137b98?)
	/home/christian/workspace/mondoo/github.com/cnquery/providers/azure/provider/provider.go:281 +0xe5
```
