### ISSUE TITLE
reporter panics when no policy is applicable

### ISSUE THREAD

**Issue by chris-rock** [mondoohq/cnspec#786]
**Describe the bug**

```
goroutine 1 [running]:
go.mondoo.com/cnspec/cli/reporter.ReportCollectionToJSON(0x14004804640, {0x10ae332b8, 0x14002dcd0c0})
	/Users/chris/go/src/go.mondoo.com/cnspec/cli/reporter/json.go:64 +0x3c
go.mondoo.com/cnspec/cli/reporter.(*Reporter).Print(0x16f3477d8?, 0x14004804640, {0x10adfb968, 0x14000138028})
	/Users/chris/go/src/go.mondoo.com/cnspec/cli/reporter/reporter.go:95 +0x314
go.mondoo.com/cnspec/apps/cnspec/cmd.printReports(0x107d24bc2?, 0x14002878a00, 0x10a8a47e0?)
	/Users/chris/go/src/go.mondoo.com/cnspec/apps/cnspec/cmd/scan.go:715 +0xa4
go.mondoo.com/cnspec/apps/cnspec/cmd.glob..func22(0x0?, {0x14002dac0a0, 0x1, 0x5}, 0x0?, 0x0?)
	/Users/chris/go/src/go.mondoo.com/cnspec/apps/cnspec/cmd/scan.go:417 +0x13c
go.mondoo.com/cnquery/apps/cnquery/cmd/builder.scanGcpProjectCmd.func1(0x14003331800?, {0x14002dac0a0?, 0x4?, 0x107d215b7?})
	/Users/chris/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20230920063559-f7739318c068/apps/cnquery/cmd/builder/builder.go:406 +0x30
github.com/spf13/cobra.(*Command).execute(0x14003351800, {0x14002dac050, 0x5, 0x5})
	/Users/chris/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x640
github.com/spf13/cobra.(*Command).ExecuteC(0x10f895540)
	/Users/chris/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x320
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/chris/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
go.mondoo.com/cnspec/apps/cnspec/cmd.Execute()
	/Users/chris/go/src/go.mondoo.com/cnspec/apps/cnspec/cmd/root.go:79 +0x24
main.main()
	/Users/chris/go/src/go.mondoo.com/cnspec/apps/cnspec/cnspec.go:6 +0x1c
```

This happens when you try to scan with a policy that has no applicable policy, normally the output looks like:

```
Asset: GCP project test
------------------------------

error: rpc error: code = InvalidArgument desc = asset doesn't support any policies
```

**To Reproduce**

Scan with a policy that is not applicable to the asset.

**Expected behavior**

Json report is created and the error for the asset is included.

**Comment by vjeffrey** [comment]
this seems to be working now
```
[2/10/23 23:43:45] ❯ cnspec scan aws -f ~/Desktop/work/terraform.mql.yaml
→ loaded configuration from /Users/vj/.config/mondoo/mondoo.yml using source default
→ using service account credentials
! Scanning with local bundles will switch into --incognito mode by default. Your results will not be sent upstream.
→ discover related assets for 1 asset(s)

 AWS Account mondoo-dev (921877552404) ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────    X score


Asset: AWS Account mondoo-dev (921877552404)
--------------------------------------------

error: rpc error: code = InvalidArgument desc = asset doesn't support any policies


Scanned 1 assets

AWS Account
    X AWS Account mondoo-dev (921877552404)


~/go/src/go.mondoo.io/cnquery vj/initfixes*
[2/10/23 23:44:54] ❯ cnspec version
cnspec 9.0.0-beta12 (93682b7, 2023-10-02T11:43:30Z)
```
