### ISSUE TITLE
serve with panic

### ISSUE THREAD

**Issue by chris-rock** [mondoohq/cnspec#789]
**Describe the bug**

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x100cd07a0]

goroutine 38 [running]:
go.mondoo.com/cnquery/providers.(*Runtime).DetectProvider(0x14000910dd0, 0x14000216ea0)
	/Users/chris/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20231002111758-82a0179e7dbd/providers/runtime.go:173 +0x1a0
go.mondoo.com/cnquery/providers.(*coordinator).RuntimeFor(0x101fd9360, 0x14000216ea0, 0x0?)
	/Users/chris/go/pkg/mod/go.mondoo.com/cnquery@v0.0.0-20231002111758-82a0179e7dbd/providers/coordinator.go:320 +0x1c8
go.mondoo.com/cnspec/policy/scan.(*LocalScanner).distributeJob(0x1400070e240, 0x1400027e2a0, {0x1016680a8, 0x140005ef140}, 0x1400027e310)
	/Users/chris/go/src/go.mondoo.com/cnspec/policy/scan/local_scanner.go:240 +0x4bc
go.mondoo.com/cnspec/policy/scan.(*LocalScanner).Run(0x101668070?, {0x1016680a8, 0x140005ef140}, 0x1400027e2a0)
	/Users/chris/go/src/go.mondoo.com/cnspec/policy/scan/local_scanner.go:150 +0x68
go.mondoo.com/cnspec/apps/cnspec/cmd.RunScan(0x1400093ab40, {0x1400076fe60?, 0x1?, 0x1?})
	/Users/chris/go/src/go.mondoo.com/cnspec/apps/cnspec/cmd/scan.go:335 +0x380
go.mondoo.com/cnspec/apps/cnspec/cmd.glob..func15.1()
	/Users/chris/go/src/go.mondoo.com/cnspec/apps/cnspec/cmd/serve.go:96 +0x40
go.mondoo.com/cnspec/apps/cnspec/cmd/backgroundjob.Serve.func1(0x1400018ede0, 0x676e69776f6c6c6f?)
	/Users/chris/go/src/go.mondoo.com/cnspec/apps/cnspec/cmd/backgroundjob/serve_unix.go:48 +0x144
created by go.mondoo.com/cnspec/apps/cnspec/cmd/backgroundjob.Serve in goroutine 1
	/Users/chris/go/src/go.mondoo.com/cnspec/apps/cnspec/cmd/backgroundjob/serve_unix.go:35 +0x2d4
```

**To Reproduce**

Run cnspec serve authenticated with Mondoo Platform

```
cnspec serve
```

**Expected behavior**

Upstream reporting works as expected

**Comment by vjeffrey** [comment]
this seems to be working now,
```
~/go/src/go.mondoo.io/cnspec main*
[3/10/23 08:45:41] ❯ go run apps/cnspec/cnspec.go serve
→ loaded configuration from /Users/vj/.config/mondoo/mondoo.yml using source default
→ start cnspec client=//agents.api.mondoo.app/spaces/frosty-neumann-161734/agents/-service_account=//agents.api.mondoo.app/spaces/frosty-neumann-161734/serviceaccounts/- space=//captain.api.mondoo.app/spaces/frosty-neumann-161734 version=unstable
→ using service account credentials
→ configure inventory to scan local operating system
→ start cnspec background service
→ scan interval is 60 minute(s) with a splay of 60 minutes(s)
→ discover related assets for 1 asset(s)
→ synchronize assets
→ scan for asset VictoriaJeffrey.local (macOS) completed
→ next scan in 1h5m32.596226344s
```
