### ISSUE TITLE
cnspec v8 panic on report printout with multi-asset scan

### ISSUE THREAD

**Issue by vjeffrey** [mondoohq/cnspec#814]
```

panic: runtime error: index out of range [1] with length 0

goroutine 1 [running]:
go.mondoo.com/cnspec/cli/reporter.(*defaultReporter).printSummary(0x14001a61ab8, {0x140047d85a0, 0xf, 0x3?})
	/home/runner/_work/cnspec/cnspec/cli/reporter/print_compact.go:174 +0xbe0
go.mondoo.com/cnspec/cli/reporter.(*defaultReporter).print(0x14001a61ab8)
	/home/runner/_work/cnspec/cnspec/cli/reporter/print_compact.go:71 +0x230
go.mondoo.com/cnspec/cli/reporter.(*Reporter).Print(0x1092d3835?, 0x7?, {0x10c3a4338?, 0x140001ae028?})
	/home/runner/_work/cnspec/cnspec/cli/reporter/reporter.go:53 +0xe0
go.mondoo.com/cnspec/apps/cnspec/cmd.printReports(0x1092d05a6?, 0x14000fb7720, 0x10be4d320?)
	/home/runner/_work/cnspec/cnspec/apps/cnspec/cmd/scan.go:715 +0xa4
```

**Comment by vjeffrey** [comment]
```
[5/10/23 13:51:34] ❯ ./cnspec\ 2 version
cnspec 8.28.4 (2fbca64, 2023-09-20T10:27:51Z)
```

**Comment by vjeffrey** [comment]
looks like this is only a issue when reporting to the server

**Comment by vjeffrey** [comment]
server-side fix needed for the asset urls, nothing to do in cnspec
