### ISSUE TITLE
Panic when running commands

### ISSUE THREAD

**Issue by tas50** [mondoohq/cnspec#859]
On my pi every command crashes:

```
pi@adsbexchange:~ $ cnquery shell
panic: shell flag redefined: sudo

goroutine 1 [running]:
github.com/spf13/pflag.(*FlagSet).AddFlag(0x28e7400, 0x2a6c320)
	/home/runner/go/pkg/mod/github.com/spf13/pflag@v1.0.6-0.20201009195203-85dd5c8bc61c/flag.go:855 +0x638
github.com/spf13/pflag.(*FlagSet).VarPF(0x28e7400, {0x11ff38c, 0x29b5ed8}, {0x28b8fc8, 0x4}, {0x0, 0x0}, {0x2c259a0, 0x1d})
	/home/runner/go/pkg/mod/github.com/spf13/pflag@v1.0.6-0.20201009195203-85dd5c8bc61c/flag.go:838 +0x148
github.com/spf13/pflag.(*FlagSet).BoolVarP(0x28e7400, 0x29b5ed8, {0x28b8fc8, 0x4}, {0x0, 0x0}, 0x0, {0x2c259a0, 0x1d})
	/home/runner/go/pkg/mod/github.com/spf13/pflag@v1.0.6-0.20201009195203-85dd5c8bc61c/bool.go:55 +0x64
github.com/spf13/pflag.(*FlagSet).BoolP(...)
	/home/runner/go/pkg/mod/github.com/spf13/pflag@v1.0.6-0.20201009195203-85dd5c8bc61c/bool.go:80
github.com/spf13/pflag.(*FlagSet).Bool(...)
	/home/runner/go/pkg/mod/github.com/spf13/pflag@v1.0.6-0.20201009195203-85dd5c8bc61c/bool.go:74
go.mondoo.com/cnquery/v9/cli/providers.attachFlag(0x28e7400, {{0x28b8fc8, 0x4}, {0x0, 0x0}, {0x28b8fd0, 0x5}, {0x2c259a0, 0x1d}, 0x1, ...})
	/home/runner/_work/cnquery/cnquery/cli/providers/providers.go:272 +0x244
go.mondoo.com/cnquery/v9/cli/providers.attachFlags(...)
	/home/runner/_work/cnquery/cnquery/cli/providers/providers.go:310
go.mondoo.com/cnquery/v9/cli/providers.setConnector(0x2990080, 0x2a6c280, 0x1093a4c, 0x1aed0a8)
	/home/runner/_work/cnquery/cnquery/cli/providers/providers.go:495 +0x29c
go.mondoo.com/cnquery/v9/cli/providers.setDefaultConnector(0x2990080, 0x2a6c280, 0x2d1ff8c)
	/home/runner/_work/cnquery/cnquery/cli/providers/providers.go:180 +0xcc
go.mondoo.com/cnquery/v9/cli/providers.attachProvidersToCmd(0x2d8b9c0, 0x2d1ff8c)
	/home/runner/_work/cnquery/cnquery/cli/providers/providers.go:161 +0x214
go.mondoo.com/cnquery/v9/cli/providers.attachProviders(...)
	/home/runner/_work/cnquery/cnquery/cli/providers/providers.go:133
go.mondoo.com/cnquery/v9/cli/providers.AttachCLIs(0x1aecc58, {0x2d1ff60, 0x3, 0x3})
	/home/runner/_work/cnquery/cnquery/cli/providers/providers.go:48 +0x108
go.mondoo.com/cnquery/v9/apps/cnquery/cmd.Execute()
	/home/runner/_work/cnquery/cnquery/apps/cnquery/cmd/root.go:48 +0x110
main.main()
	/home/runner/_work/cnquery/cnquery/apps/cnquery/cnquery.go:9 +0x14
```

```
pi@adsbexchange:~ $ cnspec version
panic: shell flag redefined: sudo

goroutine 1 [running]:
github.com/spf13/pflag.(*FlagSet).AddFlag(0x287a100, 0x298a960)
	/home/runner/go/pkg/mod/github.com/spf13/pflag@v1.0.6-0.20201009195203-85dd5c8bc61c/flag.go:855 +0x638
github.com/spf13/pflag.(*FlagSet).VarPF(0x287a100, {0x139ef10, 0x282a588}, {0x2616cc8, 0x4}, {0x0, 0x0}, {0x26c8240, 0x1d})
	/home/runner/go/pkg/mod/github.com/spf13/pflag@v1.0.6-0.20201009195203-85dd5c8bc61c/flag.go:838 +0x148
github.com/spf13/pflag.(*FlagSet).BoolVarP(0x287a100, 0x282a588, {0x2616cc8, 0x4}, {0x0, 0x0}, 0x0, {0x26c8240, 0x1d})
	/home/runner/go/pkg/mod/github.com/spf13/pflag@v1.0.6-0.20201009195203-85dd5c8bc61c/bool.go:55 +0x64
github.com/spf13/pflag.(*FlagSet).BoolP(...)
	/home/runner/go/pkg/mod/github.com/spf13/pflag@v1.0.6-0.20201009195203-85dd5c8bc61c/bool.go:80
github.com/spf13/pflag.(*FlagSet).Bool(...)
	/home/runner/go/pkg/mod/github.com/spf13/pflag@v1.0.6-0.20201009195203-85dd5c8bc61c/bool.go:74
go.mondoo.com/cnquery/v9/cli/providers.attachFlag(0x287a100, {{0x2616cc8, 0x4}, {0x0, 0x0}, {0x2616cd0, 0x5}, {0x26c8240, 0x1d}, 0x1, ...})
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery/v9@v9.2.1/cli/providers/providers.go:272 +0x244
go.mondoo.com/cnquery/v9/cli/providers.attachFlags(...)
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery/v9@v9.2.1/cli/providers/providers.go:310
go.mondoo.com/cnquery/v9/cli/providers.setConnector(0x2653ec0, 0x298a8c0, 0x1215e30, 0x1d55bf8)
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery/v9@v9.2.1/cli/providers/providers.go:495 +0x29c
go.mondoo.com/cnquery/v9/cli/providers.setDefaultConnector(0x2653ec0, 0x298a8c0, 0x2957f7c)
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery/v9@v9.2.1/cli/providers/providers.go:180 +0xcc
go.mondoo.com/cnquery/v9/cli/providers.attachProvidersToCmd(0x2910120, 0x2957f7c)
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery/v9@v9.2.1/cli/providers/providers.go:161 +0x214
go.mondoo.com/cnquery/v9/cli/providers.attachProviders(...)
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery/v9@v9.2.1/cli/providers/providers.go:133
go.mondoo.com/cnquery/v9/cli/providers.AttachCLIs(0x1d55638, {0x2957f8c, 0x4, 0x4})
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery/v9@v9.2.1/cli/providers/providers.go:48 +0x108
go.mondoo.com/cnspec/v9/apps/cnspec/cmd.Execute()
	/home/runner/_work/cnspec/cnspec/apps/cnspec/cmd/root.go:85 +0x154
main.main()
	/home/runner/_work/cnspec/cnspec/apps/cnspec/cnspec.go:9 +0x14
```

**Comment by arlimus** [comment]
Fixed with os-9.0.14. 
Also: we should add a layer to prevent duplicate flags from being added proactively, but print a warning to make sure we remediate it
