### ISSUE TITLE
panic in os provider on mac

### ISSUE THREAD

**Issue by tas50** [mondoohq/cnspec#860]
**Describe the bug**

```
~/dev  sudo cnspec scan
Password:
→ no provider specified, defaulting to local. Use --help to see all providers.
→ found a new version for 'os' provider installed=9.0.13 latest=9.0.14
→ successfully installed os provider path=/Library/Mondoo/providers/os version=9.0.14
→ loaded configuration from /Users/tsmith/.config/mondoo/mondoo.yml using source default
→ using service account credentials
→ discover related assets for 1 asset(s)
→ synchronize assets

 Tim-Smith.local ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━───────────────────────────────────────  78%


panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8 pc=0x1059c2830]

goroutine 4228 [running]:
go.mondoo.com/cnquery/v9/providers/os/resources.(*mqlProcess).MqlID(0x140001c6390?)
	/home/runner/_work/cnquery/cnquery/providers/os/resources/os.lr.go:8728
go.mondoo.com/cnquery/v9/llx.resource2result({0x106040500, 0x0}, {0x14000a77568, 0x8})
	/home/runner/_work/cnquery/cnquery/llx/data_conversions.go:319 +0x54
go.mondoo.com/cnquery/v9/llx.raw2primitive({0x106040500, 0x0}, {0x14000a77568, 0x8})
	/home/runner/_work/cnquery/cnquery/llx/data_conversions.go:350 +0x14c
go.mondoo.com/cnquery/v9/llx.(*RawData).Result(0x140007476d8)
	/home/runner/_work/cnquery/cnquery/llx/data_conversions.go:375 +0x7c
go.mondoo.com/cnquery/v9/providers-sdk/v1/plugin.(*TValue[...]).ToDataRes(0x105cc1ac0?, {0x14000a77568?, 0x105a1056f?})
	/home/runner/_work/cnquery/cnquery/providers-sdk/v1/plugin/runtime.go:185 +0x1ac
go.mondoo.com/cnquery/v9/providers/os/resources.glob..func265({0x106101520?, 0x14000ae5200?})
	/home/runner/_work/cnquery/cnquery/providers/os/resources/os.lr.go:1266 +0x74
go.mondoo.com/cnquery/v9/providers/os/resources.GetData({0x106101520, 0x14000ae5200}, {0x14000a77560, 0x7}, 0x14000747898?)
	/home/runner/_work/cnquery/cnquery/providers/os/resources/os.lr.go:1906 +0x130
go.mondoo.com/cnquery/v9/providers/os/provider.(*Service).GetData(0x0?, 0x140009d5650)
	/home/runner/_work/cnquery/cnquery/providers/os/provider/provider.go:506 +0x304
go.mondoo.com/cnquery/v9/providers-sdk/v1/plugin.(*GRPCServer).GetData(0x106012640?, {0x140009d5650?, 0x140009d55e0?}, 0x0?)
	/home/runner/_work/cnquery/cnquery/providers-sdk/v1/plugin/grpc.go:113 +0x2c
go.mondoo.com/cnquery/v9/providers-sdk/v1/plugin._ProviderPlugin_GetData_Handler({0x105fb5ba0?, 0x1400059faa0}, {0x1061183c0, 0x140009eeae0}, 0x140009d55e0, 0x0)
	/home/runner/_work/cnquery/cnquery/providers-sdk/v1/plugin/plugin_grpc.pb.go:233 +0x164
google.golang.org/grpc.(*Server).processUnaryRPC(0x14000012d20, {0x10611f540, 0x14000602ea0}, 0x140009cd8c0, 0x14000426f30, 0x106e82460, 0x0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.58.3/server.go:1374 +0xb44
google.golang.org/grpc.(*Server).handleStream(0x14000012d20, {0x10611f540, 0x14000602ea0}, 0x140009cd8c0, 0x0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.58.3/server.go:1751 +0x7c4

 Tim-Smith.local ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% score
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 30
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.58.3/server.go:997 +0x160
! resolver.db> failed to store data, types don't match asset=//assets.api.mondoo.app/spaces/stupefied-agnesi-553733/assets/2WxMqQx8SA9cJjuFwOEgXVBkJkw checksum=mxSmzbAhdqaz+Vpnu1M4ygykqjwzXsb93LE0CSn6tqd7e5a+JI45eUMcAzKhGDHzDJAcmF2vn6o6DTjtIKVOGQ== data={"type":"\u001bfile"} expected=block received=file
x failed to send datapoints error="1 error occurred:\n\t* failed to store data for \"mxSmzbAhdqaz+Vpnu1M4ygykqjwzXsb93LE0CSn6tqd7e5a+JI45eUMcAzKhGDHzDJAcmF2vn6o6DTjtIKVOGQ==\", types don't match: expected block, got file\n\n"
x the 'os' provider crashed
Asset: Tim-Smith.local
----------------------
```

**Comment by tas50** [comment]
I'm not seeing this one anymore
