### ISSUE TITLE
`--discover all` for gcp creates a panic

### ISSUE THREAD

**Issue by czunker** [mondoohq/cnspec#863]
**Describe the bug**
```
cnspec scan gcp project mondoo-dev-262313 --discover all --config ~/demo.agent.credentials.json                                                            
→ loaded configuration from /home/christian/demo.agent.credentials.json using source --config
→ using service account credentials
→ discover related assets for 1 asset(s)
→ synchronize assets

 GCP Project mondoo-dev-262313                      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% score
 chris-calligo-dev                                  ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────   0%
... 79 more assets ...

 1/81 scanned                                       ━━──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────   1%

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x12b34f0]

goroutine 60 [running]:
go.mondoo.com/cnquery/v9/providers/gcp/resources.(*mqlGcpProjectComputeServiceZone).GetName(...)
	/home/runner/_work/cnquery/cnquery/providers/gcp/resources/gcp.lr.go:10986
go.mondoo.com/cnquery/v9/providers/gcp/resources.(*mqlGcpProjectComputeServiceInstance).machineType(0x0?)
	/home/runner/_work/cnquery/cnquery/providers/gcp/resources/compute.go:308 +0x50
go.mondoo.com/cnquery/v9/providers/gcp/resources.(*mqlGcpProjectComputeServiceInstance).GetMachineType.func1()
	/home/runner/_work/cnquery/cnquery/providers/gcp/resources/gcp.lr.go:11343 +0x7f
go.mondoo.com/cnquery/v9/providers-sdk/v1/plugin.GetOrCompute[...](0xc0001df780?, 0x454285)
	/home/runner/_work/cnquery/cnquery/providers-sdk/v1/plugin/runtime.go:232 +0x37
go.mondoo.com/cnquery/v9/providers/gcp/resources.(*mqlGcpProjectComputeServiceInstance).GetMachineType(0x0?)
	/home/runner/_work/cnquery/cnquery/providers/gcp/resources/gcp.lr.go:11332 +0x3f
go.mondoo.com/cnquery/v9/providers/gcp/resources.glob..func193({0x1bca390?, 0xc0001df200?})
	/home/runner/_work/cnquery/cnquery/providers/gcp/resources/gcp.lr.go:1154 +0x30
go.mondoo.com/cnquery/v9/providers/gcp/resources.GetData({0x1bca390, 0xc0001df200}, {0xc000744610, 0xb}, 0xc0007363f0?)
	/home/runner/_work/cnquery/cnquery/providers/gcp/resources/gcp.lr.go:4017 +0x16b
go.mondoo.com/cnquery/v9/providers/gcp/provider.(*Service).GetData(0x175bc00?, 0xc0007363f0)
	/home/runner/_work/cnquery/cnquery/providers/gcp/provider/provider.go:328 +0x3ea
go.mondoo.com/cnquery/v9/providers-sdk/v1/plugin.(*GRPCServer).GetData(0x182ce40?, {0xc0007363f0?, 0x4d0626?}, 0x0?)
	/home/runner/_work/cnquery/cnquery/providers-sdk/v1/plugin/grpc.go:113 +0x1e
go.mondoo.com/cnquery/v9/providers-sdk/v1/plugin._ProviderPlugin_GetData_Handler({0x175bc00?, 0xc000050dc0}, {0x1bd0598, 0xc000e626c0}, 0xc000736380, 0x0)
	/home/runner/_work/cnquery/cnquery/providers-sdk/v1/plugin/plugin_grpc.pb.go:233 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000768000, {0x1bd6fc0, 0xc0007dab60}, 0xc0009525a0, 0xc00074c000, 0x2c4ca60, 0x0)
```

**To Reproduce**

1. Run a gcp scan with `--discover all`
2. Note the error

**Expected behavior**
No panic.

**Desktop (please complete the following information):**

- cnspec 9.2.1
- gcp 9.0.11 with connectors: gcp

**Additional context**
The other assets get scanned.

**Comment by vjeffrey** [comment]
is this fixed?

**Comment by czunker** [comment]
> is this fixed?

No, I can still produce the same panic when scanning dev.

**Comment by czunker** [comment]
This happens with instances:
```
cnspec scan gcp project mondoo-dev-262313 --discover instances
```
