### ISSUE TITLE
`scan container registry` panics

### ISSUE THREAD

**Issue by czunker** [mondoohq/cnspec#865]
**Describe the bug**
```
cnspec scan container registry gcr.io/google-samples/microservices-demo/checkoutservice:v0.8.0 --config ~/demo.agent.credentials.json 
→ loaded configuration from /home/christian/demo.agent.credentials.json using source --config
→ using service account credentials
→ discover related assets for 1 asset(s)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x98 pc=0x11db168]

goroutine 1 [running]:
go.mondoo.com/cnspec/v9/policy/scan.(*LocalScanner).distributeJob(0xc0001d3ce0, 0xc0001d3d50, {0x17e78d0, 0xc000a85620}, 0xc0001d3e30)
	/home/runner/_work/cnspec/cnspec/policy/scan/local_scanner.go:338 +0xcc8
go.mondoo.com/cnspec/v9/policy/scan.(*LocalScanner).Run(0xc0001d3ce0, {0x17e78d0, 0xc000a85620}, 0xc0001d3d50)
	/home/runner/_work/cnspec/cnspec/policy/scan/local_scanner.go:158 +0x127
go.mondoo.com/cnspec/v9/apps/cnspec/cmd.RunScan(0xc000a1d180, {0x0?, 0x0?, 0x0?})
	/home/runner/_work/cnspec/cnspec/apps/cnspec/cmd/scan.go:353 +0x3e5
go.mondoo.com/cnspec/v9/apps/cnspec/cmd.glob..func13(0x22d8120?, 0xc0003a0140?, 0x2308300?)
	/home/runner/_work/cnspec/cnspec/apps/cnspec/cmd/scan.go:131 +0xd9
go.mondoo.com/cnquery/v9/cli/providers.setConnector.func2(0xc0008eab00?, {0xc00037b100?, 0x2, 0x4})
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery/v9@v9.2.1/cli/providers/providers.go:490 +0xa22
github.com/spf13/cobra.(*Command).execute(0xc000900000, {0xc00037b0c0, 0x4, 0x4})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x863
github.com/spf13/cobra.(*Command).ExecuteC(0x22be280)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
go.mondoo.com/cnspec/v9/apps/cnspec/cmd.Execute()
	/home/runner/_work/cnspec/cnspec/apps/cnspec/cmd/root.go:114 +0x1fb
main.main()
	/home/runner/_work/cnspec/cnspec/apps/cnspec/cnspec.go:9 +0xf
```

**To Reproduce**

1. Run above command
2. Note the error

**Expected behavior**
Should scan the image or at least not panic.

**Desktop (please complete the following information):**

- cnspec v9.2.1
- provider os 9.0.14

**Additional context**
Running `scan container image` with above image works.

**Comment by czunker** [comment]
Fixed with https://github.com/mondoohq/cnspec/pull/906

```
cnspec scan container registry gcr.io/google-samples/microservices-demo/checkoutservice:v0.8.0 
→ loaded configuration from /etc/opt/mondoo/mondoo.yml using source default
→ using service account credentials
→ discover related assets for 1 asset(s)
x unable to detect platform for asset gcr.io/google-samples/microservices-demo/checkoutservice@c703e33e1c7e
```
