### ISSUE TITLE
cnspec serve crash in windows

### ISSUE THREAD

**Issue by atomic111** [mondoohq/cnspec#883]
<img width="1225" alt="Screenshot 2023-10-24 at 21 41 02" src="https://github.com/mondoohq/cnspec/assets/7220740/ec86561b-82f5-4248-9eb3-d1fc3e3732d3">
<img width="284" alt="Screenshot 2023-10-24 at 21 38 28" src="https://github.com/mondoohq/cnspec/assets/7220740/0cb224a8-18c3-4222-ab15-cc9e9ca4bb4f">

**Comment by atomic111** [comment]
same issue in linux

```bash
cnspec --config /etc/opt/mondoo/mondoo.yml serve
→ loaded configuration from /etc/opt/mondoo/mondoo.yml using source --config
→ start cnspec client=//agents.api.mondoo.app/spaces/awesome-shannon-882559/agents/2XDwo4mbkgcMkxDc9jgmKlVSH3E service_account=//agents.api.mondoo.app/spaces/awesome-shannon-882559/serviceaccounts/2XDwo6tlP1wGRGJCQjtkpyfvRe1 space=//captain.api.mondoo.app/spaces/awesome-shannon-882559 version=9.3.1
→ using service account credentials
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xa0 pc=0x1164b2f]

goroutine 1 [running]:
go.mondoo.com/cnquery/v9/providers-sdk/v1/inventory.(*Asset).AddAnnotations(...)
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery/v9@v9.3.1/providers-sdk/v1/inventory/asset.go:71
go.mondoo.com/cnquery/v9/cli/inventoryloader.ParseOrUse(0x0, 0x0, 0x21?)
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery/v9@v9.3.1/cli/inventoryloader/inventory.go:143 +0x2f
go.mondoo.com/cnspec/v9/apps/cnspec/cmd.getServeConfig()
	/home/runner/_work/cnspec/cnspec/apps/cnspec/cmd/serve.go:171 +0x568
go.mondoo.com/cnspec/v9/apps/cnspec/cmd.glob..func15(0xc0003faa00?, {0x15b813e?, 0x4?, 0x15b80ea?})
	/home/runner/_work/cnspec/cnspec/apps/cnspec/cmd/serve.go:69 +0x11e
github.com/spf13/cobra.(*Command).execute(0x22b1780, {0xc000179280, 0x2, 0x2})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x863
github.com/spf13/cobra.(*Command).ExecuteC(0x22b11c0)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
go.mondoo.com/cnspec/v9/apps/cnspec/cmd.Execute()
	/home/runner/_work/cnspec/cnspec/apps/cnspec/cmd/root.go:114 +0x1fb
main.main()
	/home/runner/_work/cnspec/cnspec/apps/cnspec/cnspec.go:9 +0xf
```

**Comment by chris-rock** [comment]
fix in by https://github.com/mondoohq/cnquery/pull/2354

**Comment by chris-rock** [comment]
Fixes with https://github.com/mondoohq/cnspec/pull/884
