### ISSUE TITLE
`cnspec vuln` panics

### ISSUE THREAD

**Issue by czunker** [mondoohq/cnspec#977]
**Describe the bug**
```
cnspec vuln
→ no provider specified, defaulting to local. Use --help to see all providers.
→ loaded configuration from /etc/opt/mondoo/mondoo.yml using source default
→ using service account credentials
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xfb05d5]

goroutine 82 [running]:
go.mondoo.com/cnquery/v9/providers-sdk/v1/plugin.(*GRPCProviderCallbackServer).GetData(0x151c660?, {0xc000210fc0?, 0x4a1726?}, 0x0?)
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery/v9@v9.9.3/providers-sdk/v1/plugin/grpc.go:162 +0x15
go.mondoo.com/cnquery/v9/providers-sdk/v1/plugin._ProviderCallback_GetData_Handler({0x142b8a0?, 0xc000eeca00}, {0x1812620, 0xc0013a2a80}, 0xc0001afc00, 0x0)
	/home/runner/go/pkg/mod/go.mondoo.com/cnquery/v9@v9.9.3/providers-sdk/v1/plugin/plugin_grpc.pb.go:464 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0004f7680, {0x1812620, 0xc0013a29c0}, {0x1818c20, 0xc000c9c4e0}, 0xc000524c60, 0xc000df2480, 0x22efcd0, 0x0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.59.0/server.go:1343 +0xe03
google.golang.org/grpc.(*Server).handleStream(0xc0004f7680, {0x1818c20, 0xc000c9c4e0}, 0xc000524c60)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.59.0/server.go:1737 +0xc4c
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.59.0/server.go:986 +0x86
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 48
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.59.0/server.go:997 +0x145
```

**To Reproduce**

2. Select '....'
4. Note the error

**Expected behavior**
I'd expect to see the vuln report.

**Desktop (please complete the following information):**

- cnspec 9.9.3
- 
**Additional context**

**Comment by chris-rock** [comment]
We should also disable the targets that we not supported. See SupportedConnectors config for the subcommand https://github.com/mondoohq/cnquery/pull/2642/files#diff-d73f4f6a951f76608a3db7b0d780ca2f8049788a39c7ec797b4ab6801960c121R68

**Comment by czunker** [comment]
> We should also disable the targets that we do not supported. See SupportedConnectors config for the subcommand https://github.com/mondoohq/cnquery/pull/2642/files#diff-d73f4f6a951f76608a3db7b0d780ca2f8049788a39c7ec797b4ab6801960c121R68

Done
